const { Prisma, PrismaClient } = require('@prisma/client')

const hillList: Prisma.HillCreateInput[] = [
  {
    remoteId: '2351',
    name: 'Binsey',
    area: 'Northern Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|Marilyn|HuMP|Fellranger|Synge|Tump|',
    height: 447,
    latitude: 54.708_795,
    longitude: -3.204_188,
  },
  {
    remoteId: '2350',
    name: 'Longlands Fell',
    area: 'Northern Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|Fellranger|Synge|Tump|',
    height: 483,
    latitude: 54.708_411,
    longitude: -3.125_313,
  },
  {
    remoteId: '2344',
    name: 'Brae Fell',
    area: 'Northern Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|Fellranger|Synge|',
    height: 586,
    latitude: 54.706_42,
    longitude: -3.105_361,
  },
  {
    remoteId: '2337',
    name: 'High Pike (Caldbeck)',
    area: 'Northern Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Hewitt|Nuttall|Fellranger|Synge|Sim|Tump|',
    height: 658,
    latitude: 54.705_416,
    longitude: -3.058_742,
  },
  {
    remoteId: '2338',
    name: 'Great Sca Fell',
    area: 'Northern Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|Fellranger|Synge|deleted Nuttall|',
    height: 651,
    latitude: 54.695_145,
    longitude: -3.100_989,
  },
  {
    remoteId: '2346',
    name: 'Meal Fell',
    area: 'Northern Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|Dewey|sub Dodd|Fellranger|Synge|',
    height: 549.4,
    latitude: 54.693_795,
    longitude: -3.113_923,
  },
  {
    remoteId: '2336',
    name: 'Carrock Fell',
    area: 'Northern Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Hewitt|Nuttall|Fellranger|Synge|Sim|Tump|',
    height: 662.3,
    latitude: 54.693_484,
    longitude: -3.022_87,
  },
  {
    remoteId: '2347',
    name: 'Great Cockup',
    area: 'Northern Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Dodd|Dewey|sub HuMP|Fellranger|Synge|Tump|',
    height: 526,
    latitude: 54.689_677,
    longitude: -3.128_766,
  },
  {
    remoteId: '2328',
    name: 'Knott',
    area: 'Northern Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Marilyn|Hewitt|Nuttall|HuMP|Fellranger|Synge|Sim|Tump|',
    height: 710,
    latitude: 54.686_982,
    longitude: -3.093_322,
  },
  {
    remoteId: '2331',
    name: 'Great Calva',
    area: 'Northern Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Hewitt|Nuttall|HuMP|sub Marilyn|Fellranger|Synge|Sim|Tump|',
    height: 691,
    latitude: 54.670_77,
    longitude: -3.101_074,
  },
  {
    remoteId: '2333',
    name: 'Bakestall',
    area: 'Northern Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|Fellranger|Synge|',
    height: 673,
    latitude: 54.666_457,
    longitude: -3.138_898,
  },
  {
    remoteId: '2329',
    name: 'Bowscale Fell',
    area: 'Northern Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Hewitt|Nuttall|Fellranger|Synge|Sim|Tump|',
    height: 702,
    latitude: 54.665_538,
    longitude: -3.035_037,
  },
  {
    remoteId: '2503',
    name: 'Sale Fell',
    area: 'North Western Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|HuMP|Fellranger|Synge|Tump|',
    height: 359,
    latitude: 54.655_627,
    longitude: -3.250_157,
  },
  {
    remoteId: '2348',
    name: 'Souther Fell',
    area: 'Northern Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|Dodd|Dewey|Fellranger|Synge|Tump|',
    height: 522,
    latitude: 54.653_236,
    longitude: -3.001_663,
  },
  {
    remoteId: '2340',
    name: 'Mungrisdale Common',
    area: 'Northern Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Synge|',
    height: 631.8,
    latitude: 54.653_232,
    longitude: -3.068_359,
  },
  {
    remoteId: '2332',
    name: 'Bannerdale Crags',
    area: 'Northern Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Hewitt|Nuttall|Fellranger|Synge|Sim|Tump|',
    height: 684.1,
    latitude: 54.651_95,
    longitude: -3.031_731,
  },
  {
    remoteId: '2319',
    name: 'Skiddaw',
    area: 'Northern Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Furth|Wainwright|Birkett|Marilyn|Hewitt|Nuttall|HuMP|Fellranger|Synge|Sim|Tump|',
    height: 930.4,
    latitude: 54.651_391,
    longitude: -3.147_761,
  },
  {
    remoteId: '2330',
    name: 'Ullock Pike',
    area: 'Northern Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|Fellranger|Synge|deleted Nuttall|',
    height: 690.4,
    latitude: 54.648_261,
    longitude: -3.172_486,
  },
  {
    remoteId: '2326',
    name: 'Long Side',
    area: 'Northern Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Hewitt|Nuttall|Fellranger|Synge|Sim|Tump|',
    height: 734,
    latitude: 54.645_505,
    longitude: -3.165_618,
  },
  {
    remoteId: '2501',
    name: 'Ling Fell',
    area: 'North Western Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|sub HuMP|Fellranger|Synge|Tump|',
    height: 374,
    latitude: 54.645_249,
    longitude: -3.272_325,
  },
  {
    remoteId: '2325',
    name: 'Carl Side',
    area: 'Northern Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|Nuttall|Fellranger|Synge|sub Sim|',
    height: 746.8,
    latitude: 54.642_398,
    longitude: -3.155_984,
  },
  {
    remoteId: '2320',
    name: 'Blencathra - Hallsfell Top',
    area: 'Northern Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Marilyn|Hewitt|Nuttall|HuMP|Fellranger|Synge|Sim|Tump|',
    height: 867.8,
    latitude: 54.639_949,
    longitude: -3.049_789,
  },
  {
    remoteId: '2321',
    name: 'Skiddaw Little Man',
    area: 'Northern Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Hewitt|Nuttall|Fellranger|Synge|Sim|Tump|',
    height: 865,
    latitude: 54.639_911,
    longitude: -3.137_629,
  },
  {
    remoteId: '2349',
    name: 'Dodd (Skiddaw)',
    area: 'Northern Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Dodd|Dewey|HuMP|Fellranger|Synge|Tump|',
    height: 502,
    latitude: 54.635_61,
    longitude: -3.172_122,
  },
  {
    remoteId: '2327',
    name: 'Lonscale Fell',
    area: 'Northern Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Hewitt|Nuttall|Fellranger|Synge|Sim|Tump|',
    height: 715,
    latitude: 54.634_357,
    longitude: -3.108_518,
  },
  {
    remoteId: '2480',
    name: 'Broom Fell',
    area: 'North Western Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|sub Dodd|Fellranger|Synge|',
    height: 510.2,
    latitude: 54.632_165,
    longitude: -3.247_904,
  },
  {
    remoteId: '2486',
    name: 'Barf',
    area: 'North Western Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|Fellranger|Synge|Tump|',
    height: 469,
    latitude: 54.629_665,
    longitude: -3.218_084,
  },
  {
    remoteId: '2489',
    name: 'Graystones',
    area: 'North Western Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|',
    height: 450.4,
    latitude: 54.627_991,
    longitude: -3.277_642,
  },
  {
    remoteId: '2345',
    name: "Lord's Seat",
    area: 'North Western Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Marilyn|Dodd|Dewey|HuMP|Fellranger|Synge|Tump|',
    height: 552,
    latitude: 54.627_823,
    longitude: -3.233_984,
  },
  {
    remoteId: '2583',
    name: 'Great Mell Fell',
    area: 'Eastern Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Marilyn|Dodd|Dewey|HuMP|Fellranger|Synge|Tump|',
    height: 537,
    latitude: 54.619_846,
    longitude: -2.935_641,
  },
  {
    remoteId: '2477',
    name: 'Whinlatter',
    area: 'North Western Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|Fellranger|Synge|',
    height: 517,
    latitude: 54.614_855,
    longitude: -3.254_033,
  },
  {
    remoteId: '2352',
    name: 'Latrigg',
    area: 'Northern Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|Fellranger|Synge|Tump|',
    height: 369,
    latitude: 54.612_432,
    longitude: -3.117_863,
  },
  {
    remoteId: '2598',
    name: 'Little Mell Fell',
    area: 'Eastern Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Marilyn|Dodd|Dewey|HuMP|Fellranger|Synge|Tump|',
    height: 505,
    latitude: 54.608_024,
    longitude: -2.894_465,
  },
  {
    remoteId: '2495',
    name: 'Fellbarrow - Mosser Fell',
    area: 'Western Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|Fellranger|Synge|Tump|',
    height: 416,
    latitude: 54.605_82,
    longitude: -3.344_699,
  },
  {
    remoteId: '2547',
    name: 'Clough Head',
    area: 'Eastern Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Hewitt|Nuttall|HuMP|Fellranger|Synge|Sim|Tump|',
    height: 726,
    latitude: 54.593_661,
    longitude: -3.032_362,
  },
  {
    remoteId: '2386',
    name: 'Grisedale Pike',
    area: 'North Western Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Marilyn|Hewitt|Nuttall|HuMP|Fellranger|Synge|Sim|Tump|',
    height: 791,
    latitude: 54.591_745,
    longitude: -3.242_071,
  },
  {
    remoteId: '2493',
    name: 'Low Fell',
    area: 'Western Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|Marilyn|HuMP|Fellranger|Synge|Tump|',
    height: 423,
    latitude: 54.591_358,
    longitude: -3.336_608,
  },
  {
    remoteId: '2627',
    name: 'High Rigg',
    area: 'Central Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|Marilyn|HuMP|Fellranger|Synge|Tump|',
    height: 355,
    latitude: 54.588_432,
    longitude: -3.071_568,
  },
  {
    remoteId: '2610',
    name: 'Gowbarrow Fell',
    area: 'Eastern Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|Fellranger|Synge|',
    height: 481.2,
    latitude: 54.588_11,
    longitude: -2.918_201,
  },
  {
    remoteId: '2395',
    name: 'Hopegill Head',
    area: 'North Western Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Hewitt|Nuttall|sub HuMP|Fellranger|Synge|Sim|Tump|',
    height: 769.6,
    latitude: 54.588_082,
    longitude: -3.261_675,
  },
  {
    remoteId: '2418',
    name: 'Whiteside',
    area: 'North Western Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|Nuttall|Fellranger|Synge|',
    height: 707,
    latitude: 54.585_912,
    longitude: -3.285_161,
  },
  {
    remoteId: '2488',
    name: 'Barrow',
    area: 'North Western Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|Fellranger|Synge|Tump|',
    height: 455,
    latitude: 54.585_66,
    longitude: -3.197_52,
  },
  {
    remoteId: '2464',
    name: 'Outerside',
    area: 'North Western Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|Dodd|Dewey|Fellranger|Synge|Tump|',
    height: 568,
    latitude: 54.582_169,
    longitude: -3.222_159,
  },
  {
    remoteId: '2500',
    name: 'Walla Crag',
    area: 'Central Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|Fellranger|Synge|',
    height: 379,
    latitude: 54.581_608,
    longitude: -3.120_377,
  },
  {
    remoteId: '2584',
    name: "Arthur's Pike",
    area: 'Far Eastern Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|Fellranger|Synge|',
    height: 533,
    latitude: 54.578_426,
    longitude: -2.835_799,
  },
  {
    remoteId: '2442',
    name: 'Causey Pike',
    area: 'North Western Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Hewitt|Nuttall|Fellranger|Synge|Sim|Tump|',
    height: 637,
    latitude: 54.576_817,
    longitude: -3.210_133,
  },
  {
    remoteId: '2484',
    name: 'Burnbank Fell',
    area: 'Western Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|Synge|',
    height: 475,
    latitude: 54.575_943,
    longitude: -3.378_34,
  },
  {
    remoteId: '2525',
    name: 'Great Dodd',
    area: 'Eastern Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Hewitt|Nuttall|HuMP|Fellranger|Synge|Sim|Tump|',
    height: 857,
    latitude: 54.575_689,
    longitude: -3.019_377,
  },
  {
    remoteId: '2432',
    name: 'Scar Crags',
    area: 'North Western Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Hewitt|Nuttall|Fellranger|Synge|Sim|Tump|',
    height: 672,
    latitude: 54.574_968,
    longitude: -3.225_951,
  },
  {
    remoteId: '2588',
    name: 'Bonscale Pike',
    area: 'Far Eastern Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|Fellranger|Synge|',
    height: 524,
    latitude: 54.573_028,
    longitude: -2.846_935,
  },
  {
    remoteId: '2374',
    name: 'Crag Hill',
    area: 'North Western Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Hewitt|Nuttall|HuMP|Fellranger|Synge|Sim|Tump|',
    height: 839.2,
    latitude: 54.571_762,
    longitude: -3.250_234,
  },
  {
    remoteId: '2372',
    name: 'Grasmoor',
    area: 'North Western Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Marilyn|Hewitt|Nuttall|HuMP|Fellranger|Synge|Sim|Tump|',
    height: 851.6,
    latitude: 54.571_635,
    longitude: -3.277_905,
  },
  {
    remoteId: '2393',
    name: 'Sail',
    area: 'North Western Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Hewitt|Nuttall|Fellranger|Synge|Sim|Tump|',
    height: 773,
    latitude: 54.571_328,
    longitude: -3.241_821,
  },
  {
    remoteId: '2623',
    name: 'Hallin Fell',
    area: 'Far Eastern Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|Marilyn|HuMP|Fellranger|Synge|Tump|',
    height: 388,
    latitude: 54.570_412,
    longitude: -2.878_498,
  },
  {
    remoteId: '2543',
    name: 'Hart Side',
    area: 'Eastern Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|Nuttall|Fellranger|Synge|sub Sim|',
    height: 756,
    latitude: 54.568_719,
    longitude: -2.992_938,
  },
  {
    remoteId: '2490',
    name: 'Cat Bells',
    area: 'North Western Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|Fellranger|Synge|Tump|',
    height: 451,
    latitude: 54.568_316,
    longitude: -3.1707,
  },
  {
    remoteId: '2460',
    name: 'Ard Crags',
    area: 'North Western Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Dodd|Dewey|HuMP|Fellranger|Synge|Tump|',
    height: 581,
    latitude: 54.566_938,
    longitude: -3.228_123,
  },
  {
    remoteId: '2534',
    name: "Watson's Dodd",
    area: 'Eastern Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|Fellranger|Synge|',
    height: 789,
    latitude: 54.566_917,
    longitude: -3.028_995,
  },
  {
    remoteId: '2458',
    name: 'Bleaberry Fell',
    area: 'Central Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|Dodd|Dewey|Fellranger|Synge|Tump|',
    height: 590,
    latitude: 54.566_37,
    longitude: -3.106_177,
  },
  {
    remoteId: '2394',
    name: 'Wandope',
    area: 'North Western Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Hewitt|Nuttall|Fellranger|Synge|Sim|Tump|',
    height: 773.9,
    latitude: 54.566_272,
    longitude: -3.257_089,
  },
  {
    remoteId: '2462',
    name: 'Blake Fell',
    area: 'Western Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Marilyn|Dodd|Dewey|HuMP|Fellranger|Synge|Tump|',
    height: 573,
    latitude: 54.564_569,
    longitude: -3.377_198,
  },
  {
    remoteId: '2526',
    name: 'Stybarrow Dodd',
    area: 'Eastern Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Hewitt|Nuttall|Fellranger|Synge|Sim|Tump|',
    height: 843.7,
    latitude: 54.561_128,
    longitude: -3.017_405,
  },
  {
    remoteId: '2434',
    name: 'Whiteless Pike',
    area: 'North Western Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Hewitt|Nuttall|Fellranger|Synge|Sim|Tump|',
    height: 660,
    latitude: 54.559_367,
    longitude: -3.269_31,
  },
  {
    remoteId: '2487',
    name: 'Raven Crag',
    area: 'Central Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|Fellranger|Synge|Tump|',
    height: 461,
    latitude: 54.559_231,
    longitude: -3.078_72,
  },
  {
    remoteId: '2465',
    name: 'Knott Rigg',
    area: 'North Western Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|Dodd|Dewey|Fellranger|Synge|Tump|',
    height: 556,
    latitude: 54.558_701,
    longitude: -3.242_613,
  },
  {
    remoteId: '2479',
    name: 'Mellbreak',
    area: 'Western Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Marilyn|Dodd|Dewey|HuMP|Fellranger|Synge|Tump|',
    height: 512,
    latitude: 54.555_581,
    longitude: -3.318_258,
  },
  {
    remoteId: '2615',
    name: 'Steel Knotts',
    area: 'Far Eastern Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|Fellranger|Synge|Tump|',
    height: 432,
    latitude: 54.555_245,
    longitude: -2.866_807,
  },
  {
    remoteId: '2554',
    name: 'Sheffield Pike',
    area: 'Eastern Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Hewitt|Nuttall|sub HuMP|Fellranger|Synge|Sim|Tump|',
    height: 676.1,
    latitude: 54.554_936,
    longitude: -2.977_002,
  },
  {
    remoteId: '2556',
    name: 'Loadpot Hill',
    area: 'Far Eastern Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Hewitt|Nuttall|Fellranger|Synge|Sim|Tump|',
    height: 672,
    latitude: 54.554_737,
    longitude: -2.842_087,
  },
  {
    remoteId: '2474',
    name: 'Gavel Fell',
    area: 'Western Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|Dodd|Dewey|Fellranger|Synge|Tump|',
    height: 524.3,
    latitude: 54.554_011,
    longitude: -3.367_472,
  },
  {
    remoteId: '2461',
    name: 'Maiden Moor',
    area: 'North Western Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|Fellranger|Synge|',
    height: 575,
    latitude: 54.553_174,
    longitude: -3.181_585,
  },
  {
    remoteId: '2502',
    name: 'Rannerdale Knotts',
    area: 'North Western Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|Fellranger|Synge|Tump|',
    height: 355,
    latitude: 54.552_643,
    longitude: -3.289_032,
  },
  {
    remoteId: '2455',
    name: 'High Seat',
    area: 'Central Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|Dewey|HuMP|Fellranger|Synge|Sim|Tump|',
    height: 609,
    latitude: 54.552_623,
    longitude: -3.103_764,
  },
  {
    remoteId: '2481',
    name: 'Hen Comb',
    area: 'Western Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Dodd|Dewey|HuMP|Fellranger|Synge|Tump|',
    height: 506.2,
    latitude: 54.550_848,
    longitude: -3.343_261,
  },
  {
    remoteId: '2612',
    name: 'Glenridding Dodd',
    area: 'Eastern Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|Fellranger|Synge|Tump|',
    height: 442,
    latitude: 54.549_47,
    longitude: -2.959_246,
  },
  {
    remoteId: '2520',
    name: 'Raise',
    area: 'Eastern Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Hewitt|Nuttall|sub HuMP|Fellranger|Synge|Sim|Tump|',
    height: 882.7,
    latitude: 54.547_718,
    longitude: -3.017_473,
  },
  {
    remoteId: '2595',
    name: 'Beda Fell',
    area: 'Far Eastern Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|Dodd|Dewey|Fellranger|Synge|Tump|',
    height: 509,
    latitude: 54.546_49,
    longitude: -2.884_399,
  },
  {
    remoteId: '2561',
    name: 'Place Fell',
    area: 'Far Eastern Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Marilyn|Hewitt|Nuttall|HuMP|Fellranger|Synge|Sim|Tump|',
    height: 657,
    latitude: 54.544_269,
    longitude: -2.920_725,
  },
  {
    remoteId: '2557',
    name: 'Wether Hill',
    area: 'Far Eastern Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|Fellranger|Synge|deleted Nuttall|',
    height: 671,
    latitude: 54.543_239,
    longitude: -2.842_453,
  },
  {
    remoteId: '2523',
    name: 'White Side',
    area: 'Eastern Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Hewitt|Nuttall|Fellranger|Synge|Sim|Tump|',
    height: 863.2,
    latitude: 54.540_904,
    longitude: -3.025_063,
  },
  {
    remoteId: '2405',
    name: 'Robinson',
    area: 'North Western Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Marilyn|Hewitt|Nuttall|HuMP|Fellranger|Synge|Sim|Tump|',
    height: 737,
    latitude: 54.540_803,
    longitude: -3.235_082,
  },
  {
    remoteId: '2478',
    name: 'High Tove',
    area: 'Central Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|Fellranger|Synge|',
    height: 515,
    latitude: 54.538_86,
    longitude: -3.100_209,
  },
  {
    remoteId: '2411',
    name: 'Hindscarth',
    area: 'North Western Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Hewitt|Nuttall|Fellranger|Synge|Sim|Tump|',
    height: 727,
    latitude: 54.537_828,
    longitude: -3.213_755,
  },
  {
    remoteId: '2496',
    name: 'Grange Fell',
    area: 'Central Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|Fellranger|Synge|Tump|',
    height: 417.2,
    latitude: 54.536_408,
    longitude: -3.137_963,
  },
  {
    remoteId: '2436',
    name: 'High Spy',
    area: 'North Western Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Hewitt|Nuttall|HuMP|sub Marilyn|Fellranger|Synge|Sim|Tump|',
    height: 653.1,
    latitude: 54.535_568,
    longitude: -3.185_141,
  },
  {
    remoteId: '2549',
    name: 'Birkhouse Moor',
    area: 'Eastern Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|Nuttall|Fellranger|Synge|sub Sim|',
    height: 717.6,
    latitude: 54.535_033,
    longitude: -2.985_32,
  },
  {
    remoteId: '2451',
    name: 'Great Borne',
    area: 'Western Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Hewitt|Nuttall|HuMP|Fellranger|Synge|Sim|Tump|',
    height: 616,
    latitude: 54.534_903,
    longitude: -3.355_427,
  },
  {
    remoteId: '2518',
    name: 'Catstye Cam',
    area: 'Eastern Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Hewitt|Nuttall|Fellranger|Synge|Sim|Tump|',
    height: 889.6,
    latitude: 54.533_472,
    longitude: -3.008_944,
  },
  {
    remoteId: '2510',
    name: 'Castle Crag',
    area: 'North Western Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Fellranger|Synge|Tump|',
    height: 290,
    latitude: 54.533_181,
    longitude: -3.161_612,
  },
  {
    remoteId: '2483',
    name: 'Armboth Fell',
    area: 'Central Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|',
    height: 475,
    latitude: 54.532_026,
    longitude: -3.089_702,
  },
  {
    remoteId: '2445',
    name: 'Starling Dodd',
    area: 'Western Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Hewitt|Nuttall|Fellranger|Synge|Sim|Tump|',
    height: 633,
    latitude: 54.529_725,
    longitude: -3.327_207,
  },
  {
    remoteId: '2577',
    name: 'The Nab',
    area: 'Far Eastern Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|Dodd|Dewey|Synge|Tump|',
    height: 576,
    latitude: 54.528_893,
    longitude: -2.875_675,
  },
  {
    remoteId: '2399',
    name: 'Red Pike (Buttermere)',
    area: 'Western Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Hewitt|Nuttall|Fellranger|Synge|Sim|Tump|',
    height: 755.3,
    latitude: 54.527_438,
    longitude: -3.298_545,
  },
  {
    remoteId: '2400',
    name: 'Dale Head',
    area: 'North Western Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Marilyn|Hewitt|Nuttall|HuMP|Fellranger|Synge|Sim|Tump|',
    height: 753,
    latitude: 54.527_238,
    longitude: -3.202_284,
  },
  {
    remoteId: '2515',
    name: 'Helvellyn',
    area: 'Eastern Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Furth|Wainwright|Birkett|Marilyn|Hewitt|Nuttall|HuMP|Sim|County Top - Historic|Fellranger|Synge|Tump|',
    height: 949.8,
    latitude: 54.527_001,
    longitude: -3.017_514,
  },
  {
    remoteId: '2614',
    name: 'Arnison Crag',
    area: 'Eastern Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|Fellranger|Synge|Tump|',
    height: 433,
    latitude: 54.526_364,
    longitude: -2.938_524,
  },
  {
    remoteId: '2579',
    name: 'Angletarn Pikes',
    area: 'Far Eastern Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|Dodd|Dewey|Fellranger|Synge|Tump|',
    height: 567,
    latitude: 54.525_312,
    longitude: -2.907_984,
  },
  {
    remoteId: '2491',
    name: 'Great Crag (Stonethwaite)',
    area: 'Central Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|Fellranger|Synge|Tump|',
    height: 449,
    latitude: 54.522_189,
    longitude: -3.129_333,
  },
  {
    remoteId: '3728',
    name: 'High Stile',
    area: 'Western Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|',
    height: 806.2,
    latitude: 54.521_578,
    longitude: -3.287_667,
  },
  {
    remoteId: '2570',
    name: 'Birks',
    area: 'Eastern Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|Nuttall|Fellranger|Synge|sub Sim|',
    height: 624,
    latitude: 54.520_711,
    longitude: -2.959_051,
  },
  {
    remoteId: '2517',
    name: 'Nethermost Pike',
    area: 'Eastern Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|Nuttall|Fellranger|Synge|sub Sim|',
    height: 891.3,
    latitude: 54.518_993,
    longitude: -3.015_446,
  },
  {
    remoteId: '2476',
    name: 'Crag Fell',
    area: 'Western Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Dodd|Dewey|HuMP|Fellranger|Synge|Tump|',
    height: 523,
    latitude: 54.516_717,
    longitude: -3.396_073,
  },
  {
    remoteId: '2438',
    name: 'Fleetwith Pike',
    area: 'Western Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Hewitt|Nuttall|HuMP|Fellranger|Synge|Sim|Tump|',
    height: 648.9,
    latitude: 54.516_562,
    longitude: -3.228_18,
  },
  {
    remoteId: '2553',
    name: 'Rest Dodd',
    area: 'Far Eastern Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Hewitt|Nuttall|HuMP|Fellranger|Synge|Sim|Tump|',
    height: 696,
    latitude: 54.514_937,
    longitude: -2.878_033,
  },
  {
    remoteId: '2582',
    name: 'Brock Crags',
    area: 'Far Eastern Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|Fellranger|Synge|',
    height: 561.2,
    latitude: 54.514_891,
    longitude: -2.902_593,
  },
  {
    remoteId: '2401',
    name: 'High Crag (Buttermere)',
    area: 'Western Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Hewitt|Nuttall|Fellranger|Synge|Sim|Tump|',
    height: 744.8,
    latitude: 54.514_628,
    longitude: -3.267_412,
  },
  {
    remoteId: '2482',
    name: 'Grike',
    area: 'Western Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|Fellranger|Synge|Tump|',
    height: 488,
    latitude: 54.513_766,
    longitude: -3.414_88,
  },
  {
    remoteId: '2530',
    name: 'High Raise (High Street)',
    area: 'Far Eastern Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Hewitt|Nuttall|Fellranger|Synge|Sim|Tump|',
    height: 803.6,
    latitude: 54.513_367,
    longitude: -2.853_779,
  },
  {
    remoteId: '2527',
    name: 'St Sunday Crag',
    area: 'Eastern Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Marilyn|Hewitt|Nuttall|HuMP|Fellranger|Synge|Sim|Tump|',
    height: 841.2,
    latitude: 54.511_94,
    longitude: -2.975_836,
  },
  {
    remoteId: '2524',
    name: 'Dollywaggon Pike',
    area: 'Eastern Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Hewitt|Nuttall|Fellranger|Synge|Sim|Tump|',
    height: 858.5,
    latitude: 54.508_693,
    longitude: -3.011_175,
  },
  {
    remoteId: '2532',
    name: 'Rampsgill Head',
    area: 'Far Eastern Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Hewitt|Nuttall|Fellranger|Synge|Sim|Tump|',
    height: 792.4,
    latitude: 54.508_092,
    longitude: -2.861_252,
  },
  {
    remoteId: '2457',
    name: 'Haystacks (Buttermere)',
    area: 'Western Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|Dodd|Dewey|Fellranger|Synge|Tump|',
    height: 597,
    latitude: 54.507_243,
    longitude: -3.247_321,
  },
  {
    remoteId: '2544',
    name: 'The Knott (High Street)',
    area: 'Far Eastern Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|Synge|deleted Nuttall|',
    height: 739,
    latitude: 54.506_316,
    longitude: -2.870_821,
  },
  {
    remoteId: '2536',
    name: 'Kidsty Pike',
    area: 'Far Eastern Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|Nuttall|Fellranger|Synge|',
    height: 781,
    latitude: 54.505_513,
    longitude: -2.854_959,
  },
  {
    remoteId: '2424',
    name: 'Grey Knotts',
    area: 'Western Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|Nuttall|Fellranger|Synge|',
    height: 697,
    latitude: 54.502_362,
    longitude: -3.210_186,
  },
  {
    remoteId: '2467',
    name: 'Rosthwaite Fell - Bessyboot',
    area: 'Southern Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|Dodd|Dewey|Fellranger|Synge|Tump|',
    height: 551,
    latitude: 54.502_198,
    longitude: -3.146_85,
  },
  {
    remoteId: '2412',
    name: 'Ullscarf',
    area: 'Central Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Hewitt|Nuttall|HuMP|Fellranger|Synge|Sim|Tump|',
    height: 723,
    latitude: 54.499_914,
    longitude: -3.095_534,
  },
  {
    remoteId: '2578',
    name: 'Hartsop Above How',
    area: 'Eastern Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|sub Dodd|Fellranger|Synge|',
    height: 586.1,
    latitude: 54.499_595,
    longitude: -2.953_955,
  },
  {
    remoteId: '2475',
    name: 'Eagle Crag',
    area: 'Central Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|sub Dodd|Fellranger|Synge|',
    height: 525,
    latitude: 54.499_056,
    longitude: -3.120_48,
  },
  {
    remoteId: '2572',
    name: 'Hartsop Dodd',
    area: 'Far Eastern Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|Nuttall|Fellranger|Synge|sub Sim|',
    height: 619,
    latitude: 54.498_538,
    longitude: -2.910_448,
  },
  {
    remoteId: '2368',
    name: 'Pillar',
    area: 'Western Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Marilyn|Hewitt|Nuttall|HuMP|Fellranger|Synge|Sim|Tump|',
    height: 892.4,
    latitude: 54.497_479,
    longitude: -3.281_134,
  },
  {
    remoteId: '2552',
    name: 'Gray Crag',
    area: 'Far Eastern Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|Fellranger|Synge|deleted Nuttall|',
    height: 698.1,
    latitude: 54.497_466,
    longitude: -2.885_363,
  },
  {
    remoteId: '2521',
    name: 'Fairfield',
    area: 'Eastern Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Marilyn|Hewitt|Nuttall|HuMP|Fellranger|Synge|Sim|Tump|',
    height: 873.3,
    latitude: 54.497_054,
    longitude: -2.991_648,
  },
  {
    remoteId: '2416',
    name: 'Brandreth',
    area: 'Western Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Hewitt|Nuttall|Fellranger|Synge|Sim|Tump|',
    height: 715,
    latitude: 54.496_479,
    longitude: -3.214_274,
  },
  {
    remoteId: '2545',
    name: 'Seat Sandal',
    area: 'Eastern Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Marilyn|Hewitt|Nuttall|HuMP|Fellranger|Synge|Sim|Tump|',
    height: 736.8,
    latitude: 54.494_857,
    longitude: -3.014_027,
  },
  {
    remoteId: '2471',
    name: 'Lank Rigg',
    area: 'Western Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Dodd|Dewey|HuMP|Fellranger|Synge|Tump|',
    height: 541,
    latitude: 54.494_811,
    longitude: -3.403_973,
  },
  {
    remoteId: '2379',
    name: 'Steeple',
    area: 'Western Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|Nuttall|Fellranger|Synge|sub Sim|',
    height: 819,
    latitude: 54.493_389,
    longitude: -3.302_174,
  },
  {
    remoteId: '2563',
    name: 'Selside Pike',
    area: 'Far Eastern Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Hewitt|Nuttall|Fellranger|Synge|Sim|Tump|',
    height: 655,
    latitude: 54.493_08,
    longitude: -2.787_925,
  },
  {
    remoteId: '2529',
    name: 'Hart Crag',
    area: 'Eastern Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Hewitt|Nuttall|Fellranger|Synge|Sim|Tump|',
    height: 823.1,
    latitude: 54.492_752,
    longitude: -2.976_954,
  },
  {
    remoteId: '2439',
    name: 'Base Brown',
    area: 'Western Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Hewitt|Nuttall|Fellranger|Synge|Sim|Tump|',
    height: 646,
    latitude: 54.492_581,
    longitude: -3.197_762,
  },
  {
    remoteId: '2463',
    name: "Sergeant's Crag",
    area: 'Central Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|Dodd|Dewey|Fellranger|Synge|Tump|',
    height: 571,
    latitude: 54.492_531,
    longitude: -3.122_463,
  },
  {
    remoteId: '2528',
    name: 'High Street',
    area: 'Far Eastern Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Marilyn|Hewitt|Nuttall|HuMP|Fellranger|Synge|Sim|Tump|',
    height: 828,
    latitude: 54.491_691,
    longitude: -2.864_86,
  },
  {
    remoteId: '2466',
    name: 'Steel Fell',
    area: 'Central Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|Dodd|Dewey|Fellranger|Synge|Tump|',
    height: 553,
    latitude: 54.491_15,
    longitude: -3.052_179,
  },
  {
    remoteId: '2373',
    name: 'Scoat Fell',
    area: 'Western Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Hewitt|Nuttall|Fellranger|Synge|Sim|Tump|',
    height: 841,
    latitude: 54.490_904,
    longitude: -3.299_224,
  },
  {
    remoteId: '2589',
    name: 'High Hartsop Dodd',
    area: 'Eastern Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|Fellranger|Synge|',
    height: 519,
    latitude: 54.488_623,
    longitude: -2.937_691,
  },
  {
    remoteId: '2425',
    name: 'Caw Fell',
    area: 'Western Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|Nuttall|Fellranger|Synge|sub Sim|',
    height: 697,
    latitude: 54.486_868,
    longitude: -3.341_256,
  },
  {
    remoteId: '2384',
    name: 'Green Gable',
    area: 'Western Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Hewitt|Nuttall|Fellranger|Synge|Sim|Tump|',
    height: 801,
    latitude: 54.485_699,
    longitude: -3.213_769,
  },
  {
    remoteId: '2533',
    name: 'Dove Crag',
    area: 'Eastern Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Hewitt|Nuttall|Fellranger|Synge|Sim|Tump|',
    height: 792,
    latitude: 54.4854,
    longitude: -2.966_93,
  },
  {
    remoteId: '2539',
    name: 'Great Rigg',
    area: 'Eastern Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Hewitt|Nuttall|Fellranger|Synge|Sim|Tump|',
    height: 766.4,
    latitude: 54.484_906,
    longitude: -2.995_692,
  },
  {
    remoteId: '2385',
    name: 'Haycock',
    area: 'Western Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Hewitt|Nuttall|sub HuMP|Fellranger|Synge|Sim|Tump|',
    height: 797,
    latitude: 54.484_568,
    longitude: -3.321_576,
  },
  {
    remoteId: '2472',
    name: 'Calf Crag',
    area: 'Central Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|Dodd|Dewey|Fellranger|Synge|Tump|',
    height: 537,
    latitude: 54.484_231,
    longitude: -3.079_493,
  },
  {
    remoteId: '2378',
    name: 'Red Pike (Wasdale)',
    area: 'Western Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Hewitt|Nuttall|Fellranger|Synge|Sim|Tump|',
    height: 826,
    latitude: 54.483_922,
    longitude: -3.289_879,
  },
  {
    remoteId: '2389',
    name: 'Glaramara',
    area: 'Southern Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Hewitt|Nuttall|HuMP|Fellranger|Synge|Sim|Tump|',
    height: 783,
    latitude: 54.483_839,
    longitude: -3.165_338,
  },
  {
    remoteId: '2541',
    name: 'Mardale Ill Bell',
    area: 'Far Eastern Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|Fellranger|Synge|deleted Nuttall|',
    height: 760,
    latitude: 54.483_418,
    longitude: -2.854_112,
  },
  {
    remoteId: '2383',
    name: 'Kirk Fell',
    area: 'Western Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Marilyn|Hewitt|Nuttall|HuMP|Fellranger|Synge|Sim|Tump|',
    height: 802,
    latitude: 54.483_323,
    longitude: -3.244_123,
  },
  {
    remoteId: '2550',
    name: 'Branstree',
    area: 'Far Eastern Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Hewitt|Nuttall|HuMP|Fellranger|Synge|Sim|Tump|',
    height: 711.5,
    latitude: 54.482_669,
    longitude: -2.807_575,
  },
  {
    remoteId: '2535',
    name: 'Thornthwaite Crag',
    area: 'Far Eastern Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Hewitt|Nuttall|Fellranger|Synge|Sim|Tump|',
    height: 784,
    latitude: 54.482_611,
    longitude: -2.878_976,
  },
  {
    remoteId: '2367',
    name: 'Great Gable',
    area: 'Western Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Marilyn|Hewitt|Nuttall|HuMP|Fellranger|Synge|Sim|Tump|',
    height: 899,
    latitude: 54.482_084,
    longitude: -3.219_296,
  },
  {
    remoteId: '2540',
    name: 'Stony Cove Pike',
    area: 'Far Eastern Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Marilyn|Hewitt|Nuttall|HuMP|Fellranger|Synge|Sim|Tump|',
    height: 763.7,
    latitude: 54.482_06,
    longitude: -2.900_08,
  },
  {
    remoteId: '2566',
    name: 'Little Hart Crag',
    area: 'Eastern Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Hewitt|Nuttall|Fellranger|Synge|Sim|Tump|',
    height: 637,
    latitude: 54.481_916,
    longitude: -2.947_169,
  },
  {
    remoteId: '2494',
    name: 'Gibson Knott',
    area: 'Central Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|Fellranger|Synge|',
    height: 420.1,
    latitude: 54.481_07,
    longitude: -3.055_825,
  },
  {
    remoteId: '2456',
    name: 'Seathwaite Fell',
    area: 'Southern Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|Fellranger|Synge|',
    height: 601.1,
    latitude: 54.480_998,
    longitude: -3.191_249,
  },
  {
    remoteId: '2564',
    name: 'Middle Dodd',
    area: 'Eastern Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|Fellranger|Synge|',
    height: 654,
    latitude: 54.477_939,
    longitude: -2.931_566,
  },
  {
    remoteId: '2537',
    name: 'Harter Fell (Mardale)',
    area: 'Far Eastern Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Hewitt|Nuttall|HuMP|sub Marilyn|Fellranger|Synge|Sim|Tump|',
    height: 779,
    latitude: 54.476_414,
    longitude: -2.835_323,
  },
  {
    remoteId: '2396',
    name: 'High Raise',
    area: 'Central Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Marilyn|Hewitt|Nuttall|HuMP|Fellranger|Synge|Sim|Tump|',
    height: 762,
    latitude: 54.475_962,
    longitude: -3.111_268,
  },
  {
    remoteId: '2498',
    name: 'Helm Crag',
    area: 'Central Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|Fellranger|Synge|Tump|',
    height: 405,
    latitude: 54.475_026,
    longitude: -3.040_823,
  },
  {
    remoteId: '2468',
    name: 'Tarn Crag (Easedale)',
    area: 'Central Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|Fellranger|Synge|',
    height: 549,
    latitude: 54.474_295,
    longitude: -3.076_006,
  },
  {
    remoteId: '2601',
    name: 'Stone Arthur',
    area: 'Eastern Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|Fellranger|Synge|',
    height: 504,
    latitude: 54.474_276,
    longitude: -3.008_366,
  },
  {
    remoteId: '2562',
    name: 'High Pike (Scandale)',
    area: 'Eastern Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|Fellranger|Synge|',
    height: 656,
    latitude: 54.470_976,
    longitude: -2.966_791,
  },
  {
    remoteId: '2538',
    name: 'Red Screes',
    area: 'Eastern Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Marilyn|Hewitt|Nuttall|HuMP|Fellranger|Synge|Sim|Tump|',
    height: 776,
    latitude: 54.470_589,
    longitude: -2.932_572,
  },
  {
    remoteId: '2407',
    name: 'Sergeant Man',
    area: 'Central Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|Fellranger|Synge|deleted Nuttall|',
    height: 736,
    latitude: 54.470_362,
    longitude: -3.102_552,
  },
  {
    remoteId: '2548',
    name: 'Froswick',
    area: 'Far Eastern Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Hewitt|Nuttall|Fellranger|Synge|Sim|Tump|',
    height: 720,
    latitude: 54.468_949,
    longitude: -2.872_974,
  },
  {
    remoteId: '2388',
    name: 'Allen Crags',
    area: 'Southern Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Hewitt|Nuttall|Fellranger|Synge|Sim|Tump|',
    height: 785,
    latitude: 54.466_367,
    longitude: -3.179_175,
  },
  {
    remoteId: '2573',
    name: 'Heron Pike (Rydal)',
    area: 'Eastern Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|Nuttall|Synge|sub Sim|',
    height: 612,
    latitude: 54.466_072,
    longitude: -2.995_142,
  },
  {
    remoteId: '2364',
    name: 'Great End',
    area: 'Southern Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Hewitt|Nuttall|Fellranger|Synge|Sim|Tump|',
    height: 909.5,
    latitude: 54.464_94,
    longitude: -3.194_548,
  },
  {
    remoteId: '2450',
    name: 'Yewbarrow',
    area: 'Western Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Hewitt|Nuttall|HuMP|sub Marilyn|Fellranger|Synge|Sim|Tump|',
    height: 628.7,
    latitude: 54.464_889,
    longitude: -3.276_86,
  },
  {
    remoteId: '2427',
    name: 'Seatallan',
    area: 'Western Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Marilyn|Hewitt|Nuttall|HuMP|Fellranger|Synge|Sim|Tump|',
    height: 692,
    latitude: 54.464_065,
    longitude: -3.328_274,
  },
  {
    remoteId: '2559',
    name: 'Tarn Crag (Sleddale)',
    area: 'Far Eastern Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Marilyn|Hewitt|Nuttall|HuMP|Fellranger|Synge|Sim|Tump|',
    height: 664,
    latitude: 54.463_458,
    longitude: -2.790_658,
  },
  {
    remoteId: '2382',
    name: 'Lingmell',
    area: 'Southern Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Hewitt|Nuttall|Fellranger|Synge|Sim|Tump|',
    height: 807,
    latitude: 54.462_803,
    longitude: -3.2213,
  },
  {
    remoteId: '2546',
    name: 'Kentmere Pike',
    area: 'Far Eastern Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Hewitt|Nuttall|Fellranger|Synge|Sim|Tump|',
    height: 730.5,
    latitude: 54.462_682,
    longitude: -2.826_034,
  },
  {
    remoteId: '2413',
    name: 'Thunacar Knott',
    area: 'Central Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|Nuttall|Fellranger|Synge|sub Sim|',
    height: 723,
    latitude: 54.462_189,
    longitude: -3.112_653,
  },
  {
    remoteId: '2596',
    name: 'Low Pike',
    area: 'Eastern Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|Fellranger|Synge|',
    height: 508,
    latitude: 54.462_069,
    longitude: -2.967_985,
  },
  {
    remoteId: '2542',
    name: 'Ill Bell',
    area: 'Far Eastern Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Hewitt|Nuttall|HuMP|Fellranger|Synge|Sim|Tump|',
    height: 757,
    latitude: 54.462_017,
    longitude: -2.870_837,
  },
  {
    remoteId: '2423',
    name: 'Pavey Ark',
    area: 'Central Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|Nuttall|Fellranger|Synge|',
    height: 700,
    latitude: 54.461_494,
    longitude: -3.105_214,
  },
  {
    remoteId: '2470',
    name: 'Blea Rigg',
    area: 'Central Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|Fellranger|Synge|',
    height: 541,
    latitude: 54.461_076,
    longitude: -3.078_806,
  },
  {
    remoteId: '2437',
    name: 'Rossett Pike',
    area: 'Southern Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Hewitt|Nuttall|Fellranger|Synge|Sim|Tump|',
    height: 651,
    latitude: 54.457_935,
    longitude: -3.159_804,
  },
  {
    remoteId: '2565',
    name: 'Grey Crag',
    area: 'Far Eastern Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Hewitt|Nuttall|Fellranger|Synge|Sim|Tump|',
    height: 638,
    latitude: 54.457_874,
    longitude: -2.777_191,
  },
  {
    remoteId: '2369',
    name: 'Esk Pike',
    area: 'Southern Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Hewitt|Nuttall|HuMP|Fellranger|Synge|Sim|Tump|',
    height: 885,
    latitude: 54.457_172,
    longitude: -3.179_219,
  },
  {
    remoteId: '2406',
    name: 'Harrison Stickle',
    area: 'Central Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Hewitt|Nuttall|Fellranger|Synge|Sim|Tump|',
    height: 736,
    latitude: 54.456_898,
    longitude: -3.109_455,
  },
  {
    remoteId: '2611',
    name: 'Nab Scar',
    area: 'Eastern Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|Fellranger|Synge|',
    height: 450,
    latitude: 54.456_414,
    longitude: -2.995_849,
  },
  {
    remoteId: '2417',
    name: 'Pike of Stickle',
    area: 'Central Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Hewitt|Nuttall|Fellranger|Synge|Sim|Tump|',
    height: 708.4,
    latitude: 54.456_393,
    longitude: -3.121_381,
  },
  {
    remoteId: '2430',
    name: 'Loft Crag',
    area: 'Central Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|Nuttall|Fellranger|Synge|sub Sim|',
    height: 681.7,
    latitude: 54.454_429,
    longitude: -3.115_991,
  },
  {
    remoteId: '2359',
    name: 'Scafell Pike',
    area: 'Southern Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Furth|Wainwright|Birkett|Marilyn|Hewitt|Nuttall|HuMP|Fellranger|Synge|Sim|County Top - Administrative|County Top - Historic|County Top - Current County and Unitary Authority|Tump|',
    height: 978.07,
    latitude: 54.454_263,
    longitude: -3.211_682,
  },
  {
    remoteId: '2459',
    name: 'Middle Fell',
    area: 'Western Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Dodd|Dewey|HuMP|Fellranger|Synge|Tump|',
    height: 582,
    latitude: 54.453_249,
    longitude: -3.311_327,
  },
  {
    remoteId: '2551',
    name: 'Yoke',
    area: 'Far Eastern Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Hewitt|Nuttall|Fellranger|Synge|Sim|Tump|',
    height: 707,
    latitude: 54.452_928,
    longitude: -2.868_731,
  },
  {
    remoteId: '2499',
    name: 'Silver How',
    area: 'Central Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|Fellranger|Synge|',
    height: 393.8,
    latitude: 54.450_687,
    longitude: -3.042_89,
  },
  {
    remoteId: '2626',
    name: 'Troutbeck Tongue',
    area: 'Far Eastern Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|Fellranger|Synge|Tump|',
    height: 364,
    latitude: 54.449_952,
    longitude: -2.892_312,
  },
  {
    remoteId: '2574',
    name: 'Shipman Knotts',
    area: 'Far Eastern Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|Fellranger|Synge|',
    height: 587,
    latitude: 54.448_577,
    longitude: -2.814_707,
  },
  {
    remoteId: '2365',
    name: 'Bowfell',
    area: 'Southern Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Hewitt|Nuttall|HuMP|sub Marilyn|Fellranger|Synge|Sim|Tump|',
    height: 902.9,
    latitude: 54.447_816,
    longitude: -3.166_242,
  },
  {
    remoteId: '2360',
    name: 'Scafell',
    area: 'Southern Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Furth|Wainwright|Birkett|Hewitt|Nuttall|HuMP|Fellranger|Synge|Sim|Tump|',
    height: 963.9,
    latitude: 54.447_498,
    longitude: -3.224_731,
  },
  {
    remoteId: '2497',
    name: 'Buckbarrow',
    area: 'Western Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|Fellranger|Synge|',
    height: 423,
    latitude: 54.443_165,
    longitude: -3.334_275,
  },
  {
    remoteId: '2607',
    name: 'Baystones',
    area: 'Far Eastern Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|HuMP|sub Marilyn|Fellranger|Tump|',
    height: 486.9,
    latitude: 54.438_194,
    longitude: -2.921_751,
  },
  {
    remoteId: '2507',
    name: 'Loughrigg Fell',
    area: 'Central Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|Marilyn|HuMP|Fellranger|Synge|Tump|',
    height: 335,
    latitude: 54.437_454,
    longitude: -3.008_355,
  },
  {
    remoteId: '2397',
    name: 'Slight Side',
    area: 'Southern Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|Fellranger|Synge|deleted Nuttall|',
    height: 762,
    latitude: 54.434_392,
    longitude: -3.219_575,
  },
  {
    remoteId: '2371',
    name: 'Crinkle Crags - Long Top',
    area: 'Southern Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Hewitt|Nuttall|HuMP|Fellranger|Synge|Sim|Tump|',
    height: 859,
    latitude: 54.433_704,
    longitude: -3.159_813,
  },
  {
    remoteId: '2454',
    name: 'Illgill Head',
    area: 'Southern Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Marilyn|Dewey|HuMP|Fellranger|Synge|Sim|Tump|',
    height: 608.8,
    latitude: 54.432_93,
    longitude: -3.282_634,
  },
  {
    remoteId: '2485',
    name: 'Lingmoor Fell',
    area: 'Southern Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|Marilyn|HuMP|Fellranger|Synge|Tump|',
    height: 470,
    latitude: 54.432_067,
    longitude: -3.076_41,
  },
  {
    remoteId: '2590',
    name: 'Sallows',
    area: 'Far Eastern Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|Dodd|Dewey|Fellranger|Synge|Tump|',
    height: 516,
    latitude: 54.428_122,
    longitude: -2.869_995,
  },
  {
    remoteId: '2419',
    name: 'Pike of Blisco',
    area: 'Southern Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Marilyn|Hewitt|Nuttall|HuMP|Fellranger|Synge|Sim|Tump|',
    height: 705,
    latitude: 54.428_111,
    longitude: -3.124_925,
  },
  {
    remoteId: '2422',
    name: 'Cold Pike',
    area: 'Southern Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Hewitt|Nuttall|Fellranger|Synge|Sim|Tump|',
    height: 700.1,
    latitude: 54.4226,
    longitude: -3.137_582,
  },
  {
    remoteId: '2609',
    name: 'Sour Howes',
    area: 'Far Eastern Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|Synge|Tump|',
    height: 483,
    latitude: 54.421_166,
    longitude: -2.883_595,
  },
  {
    remoteId: '2473',
    name: 'Whin Rigg (Wasdale)',
    area: 'Southern Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|Dodd|Dewey|Fellranger|Synge|Tump|',
    height: 537,
    latitude: 54.420_162,
    longitude: -3.309_916,
  },
  {
    remoteId: '2469',
    name: 'Hard Knott',
    area: 'Southern Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Marilyn|Dodd|Dewey|HuMP|Fellranger|Synge|Tump|',
    height: 549,
    latitude: 54.411_026,
    longitude: -3.185_029,
  },
  {
    remoteId: '2508',
    name: 'Black Fell',
    area: 'Southern Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|HuMP|Fellranger|Synge|Tump|',
    height: 323,
    latitude: 54.405_503,
    longitude: -3.017_955,
  },
  {
    remoteId: '2640',
    name: 'Wetherlam',
    area: 'Southern Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Hewitt|Nuttall|HuMP|sub Marilyn|Fellranger|Synge|Sim|Tump|',
    height: 763,
    latitude: 54.400_488,
    longitude: -3.097_966,
  },
  {
    remoteId: '2637',
    name: 'Great Carrs',
    area: 'Southern Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|Nuttall|Fellranger|Synge|sub Sim|',
    height: 785,
    latitude: 54.398_777,
    longitude: -3.124_738,
  },
  {
    remoteId: '2673',
    name: 'Holme Fell',
    area: 'Southern Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|Marilyn|HuMP|Fellranger|Synge|Tump|',
    height: 316,
    latitude: 54.396_301,
    longitude: -3.056_527,
  },
  {
    remoteId: '2635',
    name: 'Swirl How',
    area: 'Southern Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Hewitt|Nuttall|HuMP|Fellranger|Synge|Sim|Tump|',
    height: 802.4,
    latitude: 54.395_257,
    longitude: -3.121_515,
  },
  {
    remoteId: '2639',
    name: 'Grey Friar',
    area: 'Southern Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Hewitt|Nuttall|Fellranger|Synge|Sim|Tump|',
    height: 773,
    latitude: 54.393_339,
    longitude: -3.141_054,
  },
  {
    remoteId: '2643',
    name: 'Harter Fell (Eskdale)',
    area: 'Southern Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Marilyn|Hewitt|Nuttall|HuMP|Fellranger|Synge|Sim|Tump|',
    height: 653.2,
    latitude: 54.386_916,
    longitude: -3.204_523,
  },
  {
    remoteId: '2636',
    name: 'Brim Fell',
    area: 'Southern Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|Nuttall|Fellranger|Synge|',
    height: 795.9,
    latitude: 54.377_283,
    longitude: -3.124_197,
  },
  {
    remoteId: '2655',
    name: 'Green Crag',
    area: 'Southern Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|HuMP|sub Marilyn|Fellranger|Synge|Tump|',
    height: 488.7,
    latitude: 54.373_706,
    longitude: -3.232_832,
  },
  {
    remoteId: '2634',
    name: 'The Old Man of Coniston',
    area: 'Southern Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Marilyn|Hewitt|Nuttall|HuMP|County Top - Historic|Fellranger|Synge|Sim|Tump|',
    height: 802.4,
    latitude: 54.370_658,
    longitude: -3.121_445,
  },
  {
    remoteId: '2638',
    name: 'Dow Crag',
    area: 'Southern Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Hewitt|Nuttall|HuMP|Fellranger|Synge|Sim|Tump|',
    height: 778,
    latitude: 54.3703,
    longitude: -3.136_659,
  },
]

const seedHill = async (prisma: PrismaClient) => {
  const { default: pMap } = await import('p-map')

  await pMap(
    hillList,
    (hill) => {
      return prisma.hill.upsert({
        where: {
          remoteId: hill.remoteId,
        },
        update: hill,
        create: hill,
      })
    },
    { concurrency: 1 },
  )
}

module.exports = { hillList, seedHill }
