const { Prisma, PrismaClient } = require('@prisma/client')

const hillList: Prisma.HillCreateInput[] = [
  {
    remoteId: '2351',
    name: 'Binsey',
    area: 'Northern Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|Marilyn|HuMP|Fellranger|Synge|Tump|',
    height: 447,
    notes:
      'ground by windshelter 7m W at NY 22507 35528 is 10cm lower although loose rocks are higher; cairn 14m E at NY 22529 35525 is 30cm lower',
    latitude: 54.708_795,
    longitude: -3.204_188,
  },
  {
    remoteId: '2350',
    name: 'Longlands Fell',
    area: 'Northern Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|Fellranger|Synge|Tump|',
    height: 483,
    notes: 'ground 2m SSE is highest point',
    latitude: 54.708_411,
    longitude: -3.125_313,
  },
  {
    remoteId: '2344',
    name: 'Brae Fell',
    area: 'Northern Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|Fellranger|Synge|',
    height: 586,
    notes: '',
    latitude: 54.706_42,
    longitude: -3.105_361,
  },
  {
    remoteId: '2337',
    name: 'High Pike (Caldbeck)',
    area: 'Northern Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Hewitt|Nuttall|Fellranger|Synge|Sim|Tump|',
    height: 658,
    notes: 'trig point 8m N is slightly lower',
    latitude: 54.705_416,
    longitude: -3.058_742,
  },
  {
    remoteId: '2338',
    name: 'Great Sca Fell',
    area: 'Northern Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|Fellranger|Synge|deleted Nuttall|',
    height: 651,
    notes:
      'ground within 5m radius of similar height; cairn built since Wainwright volume was published',
    latitude: 54.695_145,
    longitude: -3.100_989,
  },
  {
    remoteId: '2346',
    name: 'Meal Fell',
    area: 'Northern Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|Dewey|sub Dodd|Fellranger|Synge|',
    height: 549.4,
    notes:
      'cairn is 2m higher and 65m NE of large shelter (Wainwright/Birkett summit) which is at NY 28258 33711',
    latitude: 54.693_795,
    longitude: -3.113_923,
  },
  {
    remoteId: '2336',
    name: 'Carrock Fell',
    area: 'Northern Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Hewitt|Nuttall|Fellranger|Synge|Sim|Tump|',
    height: 662.3,
    notes: '',
    latitude: 54.693_484,
    longitude: -3.022_87,
  },
  {
    remoteId: '2347',
    name: 'Great Cockup',
    area: 'Northern Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Dodd|Dewey|sub HuMP|Fellranger|Synge|Tump|',
    height: 526,
    notes: '',
    latitude: 54.689_677,
    longitude: -3.128_766,
  },
  {
    remoteId: '2328',
    name: 'Knott',
    area: 'Northern Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Marilyn|Hewitt|Nuttall|HuMP|Fellranger|Synge|Sim|Tump|',
    height: 710,
    notes: '',
    latitude: 54.686_982,
    longitude: -3.093_322,
  },
  {
    remoteId: '2331',
    name: 'Great Calva',
    area: 'Northern Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Hewitt|Nuttall|HuMP|sub Marilyn|Fellranger|Synge|Sim|Tump|',
    height: 691,
    notes: '',
    latitude: 54.670_77,
    longitude: -3.101_074,
  },
  {
    remoteId: '2333',
    name: 'Bakestall',
    area: 'Northern Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|Fellranger|Synge|',
    height: 673,
    notes: 'Wainwright cairn is 100m N at NY 26634 30855',
    latitude: 54.666_457,
    longitude: -3.138_898,
  },
  {
    remoteId: '2329',
    name: 'Bowscale Fell',
    area: 'Northern Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Hewitt|Nuttall|Fellranger|Synge|Sim|Tump|',
    height: 702,
    notes: 'cairn 50m NE at NY 33382 30609 is c 2m lower',
    latitude: 54.665_538,
    longitude: -3.035_037,
  },
  {
    remoteId: '2503',
    name: 'Sale Fell',
    area: 'North Western Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|HuMP|Fellranger|Synge|Tump|',
    height: 359,
    notes:
      'note: cairn described by Wainwright and Birkett has been largely destroyed',
    latitude: 54.655_627,
    longitude: -3.250_157,
  },
  {
    remoteId: '2348',
    name: 'Souther Fell',
    area: 'Northern Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|Dodd|Dewey|Fellranger|Synge|Tump|',
    height: 522,
    notes: '',
    latitude: 54.653_236,
    longitude: -3.001_663,
  },
  {
    remoteId: '2340',
    name: 'Mungrisdale Common',
    area: 'Northern Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Synge|',
    height: 631.8,
    notes: 'ground by cairn 120m W at NY 31055 29228 is 0.3m lower',
    latitude: 54.653_232,
    longitude: -3.068_359,
  },
  {
    remoteId: '2332',
    name: 'Bannerdale Crags',
    area: 'Northern Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Hewitt|Nuttall|Fellranger|Synge|Sim|Tump|',
    height: 684.1,
    notes: "Wainwright's cairn is 100m NE at NY 33612 29076 and is lower",
    latitude: 54.651_95,
    longitude: -3.031_731,
  },
  {
    remoteId: '2319',
    name: 'Skiddaw',
    area: 'Northern Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Furth|Wainwright|Birkett|Marilyn|Hewitt|Nuttall|HuMP|Fellranger|Synge|Sim|Tump|',
    height: 930.4,
    notes: 'note Wainwright and Birkett describe trig point as summit',
    latitude: 54.651_391,
    longitude: -3.147_761,
  },
  {
    remoteId: '2330',
    name: 'Ullock Pike',
    area: 'Northern Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|Fellranger|Synge|deleted Nuttall|',
    height: 690.4,
    notes: '',
    latitude: 54.648_261,
    longitude: -3.172_486,
  },
  {
    remoteId: '2326',
    name: 'Long Side',
    area: 'Northern Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Hewitt|Nuttall|Fellranger|Synge|Sim|Tump|',
    height: 734,
    notes: 'ground 35m W at NY 24844 28447 is 1.5m lower',
    latitude: 54.645_505,
    longitude: -3.165_618,
  },
  {
    remoteId: '2501',
    name: 'Ling Fell',
    area: 'North Western Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|sub HuMP|Fellranger|Synge|Tump|',
    height: 374,
    notes:
      'ground is 0.7m higher than trig point 70m NNW at NY17961 28593 (Wainwright,Birkett); cairn 50m N at NY 17982 28582 is 0.5m lower',
    latitude: 54.645_249,
    longitude: -3.272_325,
  },
  {
    remoteId: '2325',
    name: 'Carl Side',
    area: 'Northern Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|Nuttall|Fellranger|Synge|sub Sim|',
    height: 746.8,
    notes: '',
    latitude: 54.642_398,
    longitude: -3.155_984,
  },
  {
    remoteId: '2320',
    name: 'Blencathra - Hallsfell Top',
    area: 'Northern Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Marilyn|Hewitt|Nuttall|HuMP|Fellranger|Synge|Sim|Tump|',
    height: 867.8,
    notes: 'ground 2m N of trig point about as high',
    latitude: 54.639_949,
    longitude: -3.049_789,
  },
  {
    remoteId: '2321',
    name: 'Skiddaw Little Man',
    area: 'Northern Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Hewitt|Nuttall|Fellranger|Synge|Sim|Tump|',
    height: 865,
    notes: 'Wainwright summit is the cairn (NY 26680 27785)',
    latitude: 54.639_911,
    longitude: -3.137_629,
  },
  {
    remoteId: '2349',
    name: 'Dodd (Skiddaw)',
    area: 'Northern Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Dodd|Dewey|HuMP|Fellranger|Synge|Tump|',
    height: 502,
    notes: '',
    latitude: 54.635_61,
    longitude: -3.172_122,
  },
  {
    remoteId: '2327',
    name: 'Lonscale Fell',
    area: 'Northern Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Hewitt|Nuttall|Fellranger|Synge|Sim|Tump|',
    height: 715,
    notes: 'cairn (NY 28540 27171) is Wainwright and Birkett summit',
    latitude: 54.634_357,
    longitude: -3.108_518,
  },
  {
    remoteId: '2480',
    name: 'Broom Fell',
    area: 'North Western Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|sub Dodd|Fellranger|Synge|',
    height: 510.2,
    notes:
      'Wainwright summit cairn is 170m NW at NY 19444 27291 and is 0.9m lower',
    latitude: 54.632_165,
    longitude: -3.247_904,
  },
  {
    remoteId: '2486',
    name: 'Barf',
    area: 'North Western Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|Fellranger|Synge|Tump|',
    height: 469,
    notes: '',
    latitude: 54.629_665,
    longitude: -3.218_084,
  },
  {
    remoteId: '2489',
    name: 'Graystones',
    area: 'North Western Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|',
    height: 450.4,
    notes: '',
    latitude: 54.627_991,
    longitude: -3.277_642,
  },
  {
    remoteId: '2345',
    name: "Lord's Seat",
    area: 'North Western Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Marilyn|Dodd|Dewey|HuMP|Fellranger|Synge|Tump|',
    height: 552,
    notes: '',
    latitude: 54.627_823,
    longitude: -3.233_984,
  },
  {
    remoteId: '2583',
    name: 'Great Mell Fell',
    area: 'Eastern Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Marilyn|Dodd|Dewey|HuMP|Fellranger|Synge|Tump|',
    height: 537,
    notes: '',
    latitude: 54.619_846,
    longitude: -2.935_641,
  },
  {
    remoteId: '2477',
    name: 'Whinlatter',
    area: 'North Western Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|Fellranger|Synge|',
    height: 517,
    notes: 'highest point is ground 6m E of shelter at NY 19119 25135',
    latitude: 54.614_855,
    longitude: -3.254_033,
  },
  {
    remoteId: '2352',
    name: 'Latrigg',
    area: 'Northern Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|Fellranger|Synge|Tump|',
    height: 369,
    notes:
      "Wainwright summit position uncertain, 1203' height 80m SW at NY 27849 24654 is c.2m lower",
    latitude: 54.612_432,
    longitude: -3.117_863,
  },
  {
    remoteId: '2598',
    name: 'Little Mell Fell',
    area: 'Eastern Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Marilyn|Dodd|Dewey|HuMP|Fellranger|Synge|Tump|',
    height: 505,
    notes:
      'ground 30m W at NY 42296 24019 & 25m SW at NY 42306 24000 are just lower',
    latitude: 54.608_024,
    longitude: -2.894_465,
  },
  {
    remoteId: '2495',
    name: 'Fellbarrow - Mosser Fell',
    area: 'Western Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|Fellranger|Synge|Tump|',
    height: 416,
    notes:
      'trig point (NY 13222 24247) 5m E of cairn is Wainwright and Birkett and is 15cm lower',
    latitude: 54.605_82,
    longitude: -3.344_699,
  },
  {
    remoteId: '2547',
    name: 'Clough Head',
    area: 'Eastern Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Hewitt|Nuttall|HuMP|Fellranger|Synge|Sim|Tump|',
    height: 726,
    notes: '',
    latitude: 54.593_661,
    longitude: -3.032_362,
  },
  {
    remoteId: '2386',
    name: 'Grisedale Pike',
    area: 'North Western Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Marilyn|Hewitt|Nuttall|HuMP|Fellranger|Synge|Sim|Tump|',
    height: 791,
    notes: '',
    latitude: 54.591_745,
    longitude: -3.242_071,
  },
  {
    remoteId: '2493',
    name: 'Low Fell',
    area: 'Western Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|Marilyn|HuMP|Fellranger|Synge|Tump|',
    height: 423,
    notes: 'about 8m higher than S top (hill 3780 Loweswater Fell)',
    latitude: 54.591_358,
    longitude: -3.336_608,
  },
  {
    remoteId: '2627',
    name: 'High Rigg',
    area: 'Central Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|Marilyn|HuMP|Fellranger|Synge|Tump|',
    height: 355,
    notes: '',
    latitude: 54.588_432,
    longitude: -3.071_568,
  },
  {
    remoteId: '2610',
    name: 'Gowbarrow Fell',
    area: 'Eastern Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|Fellranger|Synge|',
    height: 481.2,
    notes:
      'trig point is Wainwright/Birkett but rocks 3m S and 8m S are higher (16 cm below FB); N knoll of S top (Hill 7833) 105m S at NY 40730 21722 is 1cm higher than rocks',
    latitude: 54.588_11,
    longitude: -2.918_201,
  },
  {
    remoteId: '2395',
    name: 'Hopegill Head',
    area: 'North Western Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Hewitt|Nuttall|sub HuMP|Fellranger|Synge|Sim|Tump|',
    height: 769.6,
    notes: '',
    latitude: 54.588_082,
    longitude: -3.261_675,
  },
  {
    remoteId: '2418',
    name: 'Whiteside',
    area: 'North Western Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|Nuttall|Fellranger|Synge|',
    height: 707,
    notes: '',
    latitude: 54.585_912,
    longitude: -3.285_161,
  },
  {
    remoteId: '2488',
    name: 'Barrow',
    area: 'North Western Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|Fellranger|Synge|Tump|',
    height: 455,
    notes: '',
    latitude: 54.585_66,
    longitude: -3.197_52,
  },
  {
    remoteId: '2464',
    name: 'Outerside',
    area: 'North Western Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|Dodd|Dewey|Fellranger|Synge|Tump|',
    height: 568,
    notes: '30cm higher than small rock 15m NE',
    latitude: 54.582_169,
    longitude: -3.222_159,
  },
  {
    remoteId: '2500',
    name: 'Walla Crag',
    area: 'Central Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|Fellranger|Synge|',
    height: 379,
    notes: '',
    latitude: 54.581_608,
    longitude: -3.120_377,
  },
  {
    remoteId: '2584',
    name: "Arthur's Pike",
    area: 'Far Eastern Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|Fellranger|Synge|',
    height: 533,
    notes:
      'probably Wainwright/Birkett summit; also cairn 190m SSE at NY 46165 20510 and knoll 50m S at NY 46056 20627 may be as high',
    latitude: 54.578_426,
    longitude: -2.835_799,
  },
  {
    remoteId: '2442',
    name: 'Causey Pike',
    area: 'North Western Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Hewitt|Nuttall|Fellranger|Synge|Sim|Tump|',
    height: 637,
    notes:
      'this summit is highest point and 3-5m higher than next 3 summits W on ridge',
    latitude: 54.576_817,
    longitude: -3.210_133,
  },
  {
    remoteId: '2484',
    name: 'Burnbank Fell',
    area: 'Western Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|Synge|',
    height: 475,
    notes: 'metal fence post is W & B; cairn 5m W is as high',
    latitude: 54.575_943,
    longitude: -3.378_34,
  },
  {
    remoteId: '2525',
    name: 'Great Dodd',
    area: 'Eastern Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Hewitt|Nuttall|HuMP|Fellranger|Synge|Sim|Tump|',
    height: 857,
    notes:
      'ground is 20cm higher than cairn at NY 34195 20557 and equal in height with ground 30m SE at NY 34228 20506; Wainwright shelter is at NY 34272 20452',
    latitude: 54.575_689,
    longitude: -3.019_377,
  },
  {
    remoteId: '2432',
    name: 'Scar Crags',
    area: 'North Western Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Hewitt|Nuttall|Fellranger|Synge|Sim|Tump|',
    height: 672,
    notes:
      '0.75m higher than ground around Wainwright cairn 120m SW at NY 20749 20598',
    latitude: 54.574_968,
    longitude: -3.225_951,
  },
  {
    remoteId: '2588',
    name: 'Bonscale Pike',
    area: 'Far Eastern Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|Fellranger|Synge|',
    height: 524,
    notes:
      'probably Wainwright summit but slightly lower than cairn 140m S at NY 45314 19950',
    latitude: 54.573_028,
    longitude: -2.846_935,
  },
  {
    remoteId: '2374',
    name: 'Crag Hill',
    area: 'North Western Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Hewitt|Nuttall|HuMP|Fellranger|Synge|Sim|Tump|',
    height: 839.2,
    notes:
      '30cm higher than trig point at NY 19270 20365. Note trig point is Wainwright summit.',
    latitude: 54.571_762,
    longitude: -3.250_234,
  },
  {
    remoteId: '2372',
    name: 'Grasmoor',
    area: 'North Western Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Marilyn|Hewitt|Nuttall|HuMP|Fellranger|Synge|Sim|Tump|',
    height: 851.6,
    notes: 'ground 100m ENE at NY 17580 20375 is 0.5m lower',
    latitude: 54.571_635,
    longitude: -3.277_905,
  },
  {
    remoteId: '2393',
    name: 'Sail',
    area: 'North Western Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Hewitt|Nuttall|Fellranger|Synge|Sim|Tump|',
    height: 773,
    notes: 'cairn is at NY 19821 20281',
    latitude: 54.571_328,
    longitude: -3.241_821,
  },
  {
    remoteId: '2623',
    name: 'Hallin Fell',
    area: 'Far Eastern Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|Marilyn|HuMP|Fellranger|Synge|Tump|',
    height: 388,
    notes: 'ground 45m SSE at NY 43323 19781 is of similar height',
    latitude: 54.570_412,
    longitude: -2.878_498,
  },
  {
    remoteId: '2543',
    name: 'Hart Side',
    area: 'Eastern Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|Nuttall|Fellranger|Synge|sub Sim|',
    height: 756,
    notes:
      'rock 6m NW is as high; NW cairn is at NY 35887 19748 and SE cairn at NY 35912 19734 and both are lower',
    latitude: 54.568_719,
    longitude: -2.992_938,
  },
  {
    remoteId: '2490',
    name: 'Cat Bells',
    area: 'North Western Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|Fellranger|Synge|Tump|',
    height: 451,
    notes: 'tiny flat cairn no longer exists',
    latitude: 54.568_316,
    longitude: -3.1707,
  },
  {
    remoteId: '2460',
    name: 'Ard Crags',
    area: 'North Western Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Dodd|Dewey|HuMP|Fellranger|Synge|Tump|',
    height: 581,
    notes: 'cairn described by Wainwright is no longer present',
    latitude: 54.566_938,
    longitude: -3.228_123,
  },
  {
    remoteId: '2534',
    name: "Watson's Dodd",
    area: 'Eastern Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|Fellranger|Synge|',
    height: 789,
    notes: '',
    latitude: 54.566_917,
    longitude: -3.028_995,
  },
  {
    remoteId: '2458',
    name: 'Bleaberry Fell',
    area: 'Central Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|Dodd|Dewey|Fellranger|Synge|Tump|',
    height: 590,
    notes:
      'rock 30m SE of wind shelter is as high, wind shelter is Wainwright summit',
    latitude: 54.566_37,
    longitude: -3.106_177,
  },
  {
    remoteId: '2394',
    name: 'Wandope',
    area: 'North Western Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Hewitt|Nuttall|Fellranger|Synge|Sim|Tump|',
    height: 773.9,
    notes: '',
    latitude: 54.566_272,
    longitude: -3.257_089,
  },
  {
    remoteId: '2462',
    name: 'Blake Fell',
    area: 'Western Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Marilyn|Dodd|Dewey|HuMP|Fellranger|Synge|Tump|',
    height: 573,
    notes: '',
    latitude: 54.564_569,
    longitude: -3.377_198,
  },
  {
    remoteId: '2526',
    name: 'Stybarrow Dodd',
    area: 'Eastern Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Hewitt|Nuttall|Fellranger|Synge|Sim|Tump|',
    height: 843.7,
    notes: 'ground is 20cm higher than cairn (NY 34296 18923)',
    latitude: 54.561_128,
    longitude: -3.017_405,
  },
  {
    remoteId: '2434',
    name: 'Whiteless Pike',
    area: 'North Western Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Hewitt|Nuttall|Fellranger|Synge|Sim|Tump|',
    height: 660,
    notes: '',
    latitude: 54.559_367,
    longitude: -3.269_31,
  },
  {
    remoteId: '2487',
    name: 'Raven Crag',
    area: 'Central Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|Fellranger|Synge|Tump|',
    height: 461,
    notes: '',
    latitude: 54.559_231,
    longitude: -3.078_72,
  },
  {
    remoteId: '2465',
    name: 'Knott Rigg',
    area: 'North Western Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|Dodd|Dewey|Fellranger|Synge|Tump|',
    height: 556,
    notes: '',
    latitude: 54.558_701,
    longitude: -3.242_613,
  },
  {
    remoteId: '2479',
    name: 'Mellbreak',
    area: 'Western Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Marilyn|Dodd|Dewey|HuMP|Fellranger|Synge|Tump|',
    height: 512,
    notes:
      'cairn described by Wainwright no longer present but may have been on small rocky outcrop 55m S at NY 14839 18558; this is 2m lower',
    latitude: 54.555_581,
    longitude: -3.318_258,
  },
  {
    remoteId: '2615',
    name: 'Steel Knotts',
    area: 'Far Eastern Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|Fellranger|Synge|Tump|',
    height: 432,
    notes: '',
    latitude: 54.555_245,
    longitude: -2.866_807,
  },
  {
    remoteId: '2554',
    name: 'Sheffield Pike',
    area: 'Eastern Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Hewitt|Nuttall|sub HuMP|Fellranger|Synge|Sim|Tump|',
    height: 676.1,
    notes: '',
    latitude: 54.554_936,
    longitude: -2.977_002,
  },
  {
    remoteId: '2556',
    name: 'Loadpot Hill',
    area: 'Far Eastern Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Hewitt|Nuttall|Fellranger|Synge|Sim|Tump|',
    height: 672,
    notes:
      'trig point is at NY 45686 18123 and is 40cm lower; boundary stone 100m ENE at NY 45731 18083 is <40cm lower',
    latitude: 54.554_737,
    longitude: -2.842_087,
  },
  {
    remoteId: '2474',
    name: 'Gavel Fell',
    area: 'Western Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|Dodd|Dewey|Fellranger|Synge|Tump|',
    height: 524.3,
    notes: 'Wainwright cairn at NY 11698 18384 is 0.2m lower',
    latitude: 54.554_011,
    longitude: -3.367_472,
  },
  {
    remoteId: '2461',
    name: 'Maiden Moor',
    area: 'North Western Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|Fellranger|Synge|',
    height: 575,
    notes:
      'Wainwright cairn 15m NW at NY 23671 18202 is 5cm lower and ground 55m SE at NY 23700 18140 is 20cm lower',
    latitude: 54.553_174,
    longitude: -3.181_585,
  },
  {
    remoteId: '2502',
    name: 'Rannerdale Knotts',
    area: 'North Western Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|Fellranger|Synge|Tump|',
    height: 355,
    notes: 'rock 2m S of cairn is actually the highest point',
    latitude: 54.552_643,
    longitude: -3.289_032,
  },
  {
    remoteId: '2455',
    name: 'High Seat',
    area: 'Central Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|Dewey|HuMP|Fellranger|Synge|Sim|Tump|',
    height: 609,
    notes:
      'rock is 0.3m higher than FB; cairn 85m ENE at NY 28788 18074 might be higher',
    latitude: 54.552_623,
    longitude: -3.103_764,
  },
  {
    remoteId: '2481',
    name: 'Hen Comb',
    area: 'Western Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Dodd|Dewey|HuMP|Fellranger|Synge|Tump|',
    height: 506.2,
    notes: '',
    latitude: 54.550_848,
    longitude: -3.343_261,
  },
  {
    remoteId: '2612',
    name: 'Glenridding Dodd',
    area: 'Eastern Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|Fellranger|Synge|Tump|',
    height: 442,
    notes: '',
    latitude: 54.549_47,
    longitude: -2.959_246,
  },
  {
    remoteId: '2520',
    name: 'Raise',
    area: 'Eastern Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Hewitt|Nuttall|sub HuMP|Fellranger|Synge|Sim|Tump|',
    height: 882.7,
    notes: '',
    latitude: 54.547_718,
    longitude: -3.017_473,
  },
  {
    remoteId: '2595',
    name: 'Beda Fell',
    area: 'Far Eastern Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|Dodd|Dewey|Fellranger|Synge|Tump|',
    height: 509,
    notes: 'ground 140m SW at NY 42800 17048 is as high',
    latitude: 54.546_49,
    longitude: -2.884_399,
  },
  {
    remoteId: '2561',
    name: 'Place Fell',
    area: 'Far Eastern Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Marilyn|Hewitt|Nuttall|HuMP|Fellranger|Synge|Sim|Tump|',
    height: 657,
    notes:
      'outcrop is 0.3m higher than trig point 30m E (NY 40560 16950); cairn is Wainwright summit.',
    latitude: 54.544_269,
    longitude: -2.920_725,
  },
  {
    remoteId: '2557',
    name: 'Wether Hill',
    area: 'Far Eastern Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|Fellranger|Synge|deleted Nuttall|',
    height: 671,
    notes:
      'cairn (Wainwright/Birkett) is 30m NW at NY45571 16782; summit is 3-4m lower than ground 400m S (Hill 2927)',
    latitude: 54.543_239,
    longitude: -2.842_453,
  },
  {
    remoteId: '2523',
    name: 'White Side',
    area: 'Eastern Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Hewitt|Nuttall|Fellranger|Synge|Sim|Tump|',
    height: 863.2,
    notes: '',
    latitude: 54.540_904,
    longitude: -3.025_063,
  },
  {
    remoteId: '2405',
    name: 'Robinson',
    area: 'North Western Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Marilyn|Hewitt|Nuttall|HuMP|Fellranger|Synge|Sim|Tump|',
    height: 737,
    notes:
      'rock 4m SW is just lower; rock under cairn 10m W at NY 20180 16873 is c 30cm lower',
    latitude: 54.540_803,
    longitude: -3.235_082,
  },
  {
    remoteId: '2478',
    name: 'High Tove',
    area: 'Central Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|Fellranger|Synge|',
    height: 515,
    notes: 'ground 10m N of cairn is as high',
    latitude: 54.538_86,
    longitude: -3.100_209,
  },
  {
    remoteId: '2411',
    name: 'Hindscarth',
    area: 'North Western Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Hewitt|Nuttall|Fellranger|Synge|Sim|Tump|',
    height: 727,
    notes: 'several rocks nearby look higher but are not',
    latitude: 54.537_828,
    longitude: -3.213_755,
  },
  {
    remoteId: '2496',
    name: 'Grange Fell',
    area: 'Central Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|Fellranger|Synge|Tump|',
    height: 417.2,
    notes: "Wainwright's rock tor 70m SW at NY 26412 16240 is 1m - 2m lower",
    latitude: 54.536_408,
    longitude: -3.137_963,
  },
  {
    remoteId: '2436',
    name: 'High Spy',
    area: 'North Western Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Hewitt|Nuttall|HuMP|sub Marilyn|Fellranger|Synge|Sim|Tump|',
    height: 653.1,
    notes: 'ground 7m NE and also 30m S at NY 23420 16200 is as high',
    latitude: 54.535_568,
    longitude: -3.185_141,
  },
  {
    remoteId: '2549',
    name: 'Birkhouse Moor',
    area: 'Eastern Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|Nuttall|Fellranger|Synge|sub Sim|',
    height: 717.6,
    notes: 'higher than large cairn 450m NNE at NY 36524 16393',
    latitude: 54.535_033,
    longitude: -2.985_32,
  },
  {
    remoteId: '2451',
    name: 'Great Borne',
    area: 'Western Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Hewitt|Nuttall|HuMP|Fellranger|Synge|Sim|Tump|',
    height: 616,
    notes:
      "rock is 22m S of trig point (Wainwright's summit at NY 12391 16381) and 40cm higher than rock by trig point; rock is 12m S of windshelter (Birkett's summit at NY 12395 16373) and 10cm higher than its floor; Wainwright's 'north top' is lower",
    latitude: 54.534_903,
    longitude: -3.355_427,
  },
  {
    remoteId: '2518',
    name: 'Catstye Cam',
    area: 'Eastern Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Hewitt|Nuttall|Fellranger|Synge|Sim|Tump|',
    height: 889.6,
    notes: '',
    latitude: 54.533_472,
    longitude: -3.008_944,
  },
  {
    remoteId: '2510',
    name: 'Castle Crag',
    area: 'North Western Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Fellranger|Synge|Tump|',
    height: 290,
    notes: '',
    latitude: 54.533_181,
    longitude: -3.161_612,
  },
  {
    remoteId: '2483',
    name: 'Armboth Fell',
    area: 'Central Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|',
    height: 475,
    notes: '',
    latitude: 54.532_026,
    longitude: -3.089_702,
  },
  {
    remoteId: '2445',
    name: 'Starling Dodd',
    area: 'Western Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Hewitt|Nuttall|Fellranger|Synge|Sim|Tump|',
    height: 633,
    notes: '',
    latitude: 54.529_725,
    longitude: -3.327_207,
  },
  {
    remoteId: '2577',
    name: 'The Nab',
    area: 'Far Eastern Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|Dodd|Dewey|Synge|Tump|',
    height: 576,
    notes: 'Wainwright and Birkett; ground 30m NE at NY 43440 15223 is lower',
    latitude: 54.528_893,
    longitude: -2.875_675,
  },
  {
    remoteId: '2399',
    name: 'Red Pike (Buttermere)',
    area: 'Western Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Hewitt|Nuttall|Fellranger|Synge|Sim|Tump|',
    height: 755.3,
    notes: 'cairn is at NY 16054 15453',
    latitude: 54.527_438,
    longitude: -3.298_545,
  },
  {
    remoteId: '2400',
    name: 'Dale Head',
    area: 'North Western Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Marilyn|Hewitt|Nuttall|HuMP|Fellranger|Synge|Sim|Tump|',
    height: 753,
    notes:
      'ground at cairn (Wainwright/Birkett) at NY 22310 15330 is 30cm lower',
    latitude: 54.527_238,
    longitude: -3.202_284,
  },
  {
    remoteId: '2515',
    name: 'Helvellyn',
    area: 'Eastern Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Furth|Wainwright|Birkett|Marilyn|Hewitt|Nuttall|HuMP|Sim|County Top - Historic|Fellranger|Synge|Tump|',
    height: 949.8,
    notes: 'trig point is slightly lower',
    latitude: 54.527_001,
    longitude: -3.017_514,
  },
  {
    remoteId: '2614',
    name: 'Arnison Crag',
    area: 'Eastern Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|Fellranger|Synge|Tump|',
    height: 433,
    notes: 'rock 3m S is highest point',
    latitude: 54.526_364,
    longitude: -2.938_524,
  },
  {
    remoteId: '2579',
    name: 'Angletarn Pikes',
    area: 'Far Eastern Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|Dodd|Dewey|Fellranger|Synge|Tump|',
    height: 567,
    notes: 'rock 30m to NE at NY 41354 14841 is just lower',
    latitude: 54.525_312,
    longitude: -2.907_984,
  },
  {
    remoteId: '2491',
    name: 'Great Crag (Stonethwaite)',
    area: 'Central Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|Fellranger|Synge|Tump|',
    height: 449,
    notes:
      'this is S top (Wainwright summit); top (two cairns) 80m N (Birkett) at NY 26998 14765 is 50cm lower',
    latitude: 54.522_189,
    longitude: -3.129_333,
  },
  {
    remoteId: '3728',
    name: 'High Stile',
    area: 'Western Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|',
    height: 806.2,
    notes: '30cm lower than hill 2381 270m ENE at NY 17009 14817',
    latitude: 54.521_578,
    longitude: -3.287_667,
  },
  {
    remoteId: '2570',
    name: 'Birks',
    area: 'Eastern Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|Nuttall|Fellranger|Synge|sub Sim|',
    height: 624,
    notes:
      'this is Nuttall/Subsimm/Birkett summit; cairn (Wainwright) 200m NE at NY 38179 14485 is lower',
    latitude: 54.520_711,
    longitude: -2.959_051,
  },
  {
    remoteId: '2517',
    name: 'Nethermost Pike',
    area: 'Eastern Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|Nuttall|Fellranger|Synge|sub Sim|',
    height: 891.3,
    notes:
      'Wainwright is small cairn at NY 34406 14157, cairn 20m NW is probably lower',
    latitude: 54.518_993,
    longitude: -3.015_446,
  },
  {
    remoteId: '2476',
    name: 'Crag Fell',
    area: 'Western Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Dodd|Dewey|HuMP|Fellranger|Synge|Tump|',
    height: 523,
    notes: 'SE top 100m away at NY 09815 14330 is lower',
    latitude: 54.516_717,
    longitude: -3.396_073,
  },
  {
    remoteId: '2438',
    name: 'Fleetwith Pike',
    area: 'Western Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Hewitt|Nuttall|HuMP|Fellranger|Synge|Sim|Tump|',
    height: 648.9,
    notes: 'higher ground may be hidden beneath the cairn',
    latitude: 54.516_562,
    longitude: -3.228_18,
  },
  {
    remoteId: '2553',
    name: 'Rest Dodd',
    area: 'Far Eastern Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Hewitt|Nuttall|HuMP|Fellranger|Synge|Sim|Tump|',
    height: 696,
    notes:
      "cairns 55m NNE at NY 43271 13701(Wainwright's cairn) & 80m NNW at NY 43237 13718 are lower",
    latitude: 54.514_937,
    longitude: -2.878_033,
  },
  {
    remoteId: '2582',
    name: 'Brock Crags',
    area: 'Far Eastern Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|Fellranger|Synge|',
    height: 561.2,
    notes: 'true summit is 230m E at NY 41904 13699',
    latitude: 54.514_891,
    longitude: -2.902_593,
  },
  {
    remoteId: '2401',
    name: 'High Crag (Buttermere)',
    area: 'Western Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Hewitt|Nuttall|Fellranger|Synge|Sim|Tump|',
    height: 744.8,
    notes: 'cairn to N is lower',
    latitude: 54.514_628,
    longitude: -3.267_412,
  },
  {
    remoteId: '2482',
    name: 'Grike',
    area: 'Western Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|Fellranger|Synge|Tump|',
    height: 488,
    notes: 'cairn 10m W at NY 08491 14075 is lower; ground 100m E is lower',
    latitude: 54.513_766,
    longitude: -3.414_88,
  },
  {
    remoteId: '2530',
    name: 'High Raise (High Street)',
    area: 'Far Eastern Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Hewitt|Nuttall|Fellranger|Synge|Sim|Tump|',
    height: 803.6,
    notes: '',
    latitude: 54.513_367,
    longitude: -2.853_779,
  },
  {
    remoteId: '2527',
    name: 'St Sunday Crag',
    area: 'Eastern Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Marilyn|Hewitt|Nuttall|HuMP|Fellranger|Synge|Sim|Tump|',
    height: 841.2,
    notes: '',
    latitude: 54.511_94,
    longitude: -2.975_836,
  },
  {
    remoteId: '2524',
    name: 'Dollywaggon Pike',
    area: 'Eastern Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Hewitt|Nuttall|Fellranger|Synge|Sim|Tump|',
    height: 858.5,
    notes: 'rock 7m W may be as high; cairn 30m SW at NY 34601 13046 is lower',
    latitude: 54.508_693,
    longitude: -3.011_175,
  },
  {
    remoteId: '2532',
    name: 'Rampsgill Head',
    area: 'Far Eastern Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Hewitt|Nuttall|Fellranger|Synge|Sim|Tump|',
    height: 792.4,
    notes:
      "Wainwright's cairn is 145m SW at NY 44227 12772 and is 1m lower; rock 80m SW at NY 44293 12800 & ground 90m SW at NY 44276 12801 are both of similar height",
    latitude: 54.508_092,
    longitude: -2.861_252,
  },
  {
    remoteId: '2457',
    name: 'Haystacks (Buttermere)',
    area: 'Western Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|Dodd|Dewey|Fellranger|Synge|Tump|',
    height: 597,
    notes:
      'this is the S cairn and is about 2m higher than N cairn 50m N at NY 19336 13204',
    latitude: 54.507_243,
    longitude: -3.247_321,
  },
  {
    remoteId: '2544',
    name: 'The Knott (High Street)',
    area: 'Far Eastern Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|Synge|deleted Nuttall|',
    height: 739,
    notes: '',
    latitude: 54.506_316,
    longitude: -2.870_821,
  },
  {
    remoteId: '2536',
    name: 'Kidsty Pike',
    area: 'Far Eastern Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|Nuttall|Fellranger|Synge|',
    height: 781,
    notes: '',
    latitude: 54.505_513,
    longitude: -2.854_959,
  },
  {
    remoteId: '2424',
    name: 'Grey Knotts',
    area: 'Western Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|Nuttall|Fellranger|Synge|',
    height: 697,
    notes:
      'outcrop 155m ENE at NY 21876 12581 is as high and OS bolt and cairn 45m NE of this at NY 21914 12615 is lower',
    latitude: 54.502_362,
    longitude: -3.210_186,
  },
  {
    remoteId: '2467',
    name: 'Rosthwaite Fell - Bessyboot',
    area: 'Southern Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|Dodd|Dewey|Fellranger|Synge|Tump|',
    height: 551,
    notes: '',
    latitude: 54.502_198,
    longitude: -3.146_85,
  },
  {
    remoteId: '2412',
    name: 'Ullscarf',
    area: 'Central Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Hewitt|Nuttall|HuMP|Fellranger|Synge|Sim|Tump|',
    height: 723,
    notes: '',
    latitude: 54.499_914,
    longitude: -3.095_534,
  },
  {
    remoteId: '2578',
    name: 'Hartsop Above How',
    area: 'Eastern Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|sub Dodd|Fellranger|Synge|',
    height: 586.1,
    notes:
      "local topography fits Wainwright's sketch and knoll is several metres higher than any other top on ridge; embedded rock on knoll 240m away at NY 38540 12105 is probably Wainwright's NE summit",
    latitude: 54.499_595,
    longitude: -2.953_955,
  },
  {
    remoteId: '2475',
    name: 'Eagle Crag',
    area: 'Central Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|sub Dodd|Fellranger|Synge|',
    height: 525,
    notes: '',
    latitude: 54.499_056,
    longitude: -3.120_48,
  },
  {
    remoteId: '2572',
    name: 'Hartsop Dodd',
    area: 'Far Eastern Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|Nuttall|Fellranger|Synge|sub Sim|',
    height: 619,
    notes:
      'fence post by wall (Wainwright summit) is 7m N of small cairn; larger cairn 35m NW at NY 41107 11874 is lower',
    latitude: 54.498_538,
    longitude: -2.910_448,
  },
  {
    remoteId: '2368',
    name: 'Pillar',
    area: 'Western Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Marilyn|Hewitt|Nuttall|HuMP|Fellranger|Synge|Sim|Tump|',
    height: 892.4,
    notes: '',
    latitude: 54.497_479,
    longitude: -3.281_134,
  },
  {
    remoteId: '2552',
    name: 'Gray Crag',
    area: 'Far Eastern Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|Fellranger|Synge|deleted Nuttall|',
    height: 698.1,
    notes:
      'this is Nuttall summit S of wall; Wainwright summit is N of wall at NY 42672 11869',
    latitude: 54.497_466,
    longitude: -2.885_363,
  },
  {
    remoteId: '2521',
    name: 'Fairfield',
    area: 'Eastern Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Marilyn|Hewitt|Nuttall|HuMP|Fellranger|Synge|Sim|Tump|',
    height: 873.3,
    notes: 'rock 20m SW at NY 35861 11736 is 0.3m lower',
    latitude: 54.497_054,
    longitude: -2.991_648,
  },
  {
    remoteId: '2416',
    name: 'Brandreth',
    area: 'Western Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Hewitt|Nuttall|Fellranger|Synge|Sim|Tump|',
    height: 715,
    notes:
      'Wainwright cairn 35m ENE at NY 21489 11928 and cairn 75m SE at NY 21518 11873 are both c 0.4m lower',
    latitude: 54.496_479,
    longitude: -3.214_274,
  },
  {
    remoteId: '2545',
    name: 'Seat Sandal',
    area: 'Eastern Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Marilyn|Hewitt|Nuttall|HuMP|Fellranger|Synge|Sim|Tump|',
    height: 736.8,
    notes: '30m ENE of cairn (Wainwright) at NY 34390 11515 and 40cm higher',
    latitude: 54.494_857,
    longitude: -3.014_027,
  },
  {
    remoteId: '2471',
    name: 'Lank Rigg',
    area: 'Western Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Dodd|Dewey|HuMP|Fellranger|Synge|Tump|',
    height: 541,
    notes:
      'cairn 3m S is lower; cairn 200m SW at NY 09024 11817 is several metres lower',
    latitude: 54.494_811,
    longitude: -3.403_973,
  },
  {
    remoteId: '2379',
    name: 'Steeple',
    area: 'Western Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|Nuttall|Fellranger|Synge|sub Sim|',
    height: 819,
    notes: '',
    latitude: 54.493_389,
    longitude: -3.302_174,
  },
  {
    remoteId: '2563',
    name: 'Selside Pike',
    area: 'Far Eastern Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Hewitt|Nuttall|Fellranger|Synge|Sim|Tump|',
    height: 655,
    notes:
      'windshelter (Wainwright & Birkett) is at NY 49073 11186 and is 75cm lower',
    latitude: 54.493_08,
    longitude: -2.787_925,
  },
  {
    remoteId: '2529',
    name: 'Hart Crag',
    area: 'Eastern Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Hewitt|Nuttall|Fellranger|Synge|Sim|Tump|',
    height: 823.1,
    notes: 'rock near Wainwright cairn 100m SE at NY 36891 11207 is as high',
    latitude: 54.492_752,
    longitude: -2.976_954,
  },
  {
    remoteId: '2439',
    name: 'Base Brown',
    area: 'Western Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Hewitt|Nuttall|Fellranger|Synge|Sim|Tump|',
    height: 646,
    notes: '',
    latitude: 54.492_581,
    longitude: -3.197_762,
  },
  {
    remoteId: '2463',
    name: "Sergeant's Crag",
    area: 'Central Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|Dodd|Dewey|Fellranger|Synge|Tump|',
    height: 571,
    notes: '',
    latitude: 54.492_531,
    longitude: -3.122_463,
  },
  {
    remoteId: '2528',
    name: 'High Street',
    area: 'Far Eastern Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Marilyn|Hewitt|Nuttall|HuMP|Fellranger|Synge|Sim|Tump|',
    height: 828,
    notes: '',
    latitude: 54.491_691,
    longitude: -2.864_86,
  },
  {
    remoteId: '2466',
    name: 'Steel Fell',
    area: 'Central Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|Dodd|Dewey|Fellranger|Synge|Tump|',
    height: 553,
    notes: 'cairn 80m E at NY 32023 11167 is 2m lower',
    latitude: 54.491_15,
    longitude: -3.052_179,
  },
  {
    remoteId: '2373',
    name: 'Scoat Fell',
    area: 'Western Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Hewitt|Nuttall|Fellranger|Synge|Sim|Tump|',
    height: 841,
    notes: '',
    latitude: 54.490_904,
    longitude: -3.299_224,
  },
  {
    remoteId: '2589',
    name: 'High Hartsop Dodd',
    area: 'Eastern Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|Fellranger|Synge|',
    height: 519,
    notes: '',
    latitude: 54.488_623,
    longitude: -2.937_691,
  },
  {
    remoteId: '2425',
    name: 'Caw Fell',
    area: 'Western Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|Nuttall|Fellranger|Synge|sub Sim|',
    height: 697,
    notes: 'cairn is Wainwright and Birkett summit',
    latitude: 54.486_868,
    longitude: -3.341_256,
  },
  {
    remoteId: '2384',
    name: 'Green Gable',
    area: 'Western Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Hewitt|Nuttall|Fellranger|Synge|Sim|Tump|',
    height: 801,
    notes: '',
    latitude: 54.485_699,
    longitude: -3.213_769,
  },
  {
    remoteId: '2533',
    name: 'Dove Crag',
    area: 'Eastern Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Hewitt|Nuttall|Fellranger|Synge|Sim|Tump|',
    height: 792,
    notes:
      'rock 15m N at NY 37458 10451 is slightly higher than edge of cairn but higher ground may exist under cairn',
    latitude: 54.4854,
    longitude: -2.966_93,
  },
  {
    remoteId: '2539',
    name: 'Great Rigg',
    area: 'Eastern Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Hewitt|Nuttall|Fellranger|Synge|Sim|Tump|',
    height: 766.4,
    notes: 'cairn (NY 35584 10395) is Wainwright',
    latitude: 54.484_906,
    longitude: -2.995_692,
  },
  {
    remoteId: '2385',
    name: 'Haycock',
    area: 'Western Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Hewitt|Nuttall|sub HuMP|Fellranger|Synge|Sim|Tump|',
    height: 797,
    notes:
      'Wainwright claims windshelter on N side of wall (NY 14475 10726) is marginally higher',
    latitude: 54.484_568,
    longitude: -3.321_576,
  },
  {
    remoteId: '2472',
    name: 'Calf Crag',
    area: 'Central Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|Dodd|Dewey|Fellranger|Synge|Tump|',
    height: 537,
    notes: '',
    latitude: 54.484_231,
    longitude: -3.079_493,
  },
  {
    remoteId: '2378',
    name: 'Red Pike (Wasdale)',
    area: 'Western Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Hewitt|Nuttall|Fellranger|Synge|Sim|Tump|',
    height: 826,
    notes: '',
    latitude: 54.483_922,
    longitude: -3.289_879,
  },
  {
    remoteId: '2389',
    name: 'Glaramara',
    area: 'Southern Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Hewitt|Nuttall|HuMP|Fellranger|Synge|Sim|Tump|',
    height: 783,
    notes:
      'Nuttall summit; Wainwright summit (cairn) 160m NE at NY 24722 10561 and cairn 55m W are lower',
    latitude: 54.483_839,
    longitude: -3.165_338,
  },
  {
    remoteId: '2541',
    name: 'Mardale Ill Bell',
    area: 'Far Eastern Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|Fellranger|Synge|deleted Nuttall|',
    height: 760,
    notes: '',
    latitude: 54.483_418,
    longitude: -2.854_112,
  },
  {
    remoteId: '2383',
    name: 'Kirk Fell',
    area: 'Western Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Marilyn|Hewitt|Nuttall|HuMP|Fellranger|Synge|Sim|Tump|',
    height: 802,
    notes: '',
    latitude: 54.483_323,
    longitude: -3.244_123,
  },
  {
    remoteId: '2550',
    name: 'Branstree',
    area: 'Far Eastern Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Hewitt|Nuttall|HuMP|Fellranger|Synge|Sim|Tump|',
    height: 711.5,
    notes: 'circular trig station 40m SE at NY 47795 09971 is 0.25m lower',
    latitude: 54.482_669,
    longitude: -2.807_575,
  },
  {
    remoteId: '2535',
    name: 'Thornthwaite Crag',
    area: 'Far Eastern Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Hewitt|Nuttall|Fellranger|Synge|Sim|Tump|',
    height: 784,
    notes:
      'beacon (Wainwright/Birkett) 45m S at NY 43138 10008 is lower. Ground in wall 10m W is of similar height',
    latitude: 54.482_611,
    longitude: -2.878_976,
  },
  {
    remoteId: '2367',
    name: 'Great Gable',
    area: 'Western Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Marilyn|Hewitt|Nuttall|HuMP|Fellranger|Synge|Sim|Tump|',
    height: 899,
    notes: '',
    latitude: 54.482_084,
    longitude: -3.219_296,
  },
  {
    remoteId: '2540',
    name: 'Stony Cove Pike',
    area: 'Far Eastern Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Marilyn|Hewitt|Nuttall|HuMP|Fellranger|Synge|Sim|Tump|',
    height: 763.7,
    notes:
      'rock is about 1m higher than Wainwright cairn 90m E at NY 41867 09997; there are several cairns in the summit area',
    latitude: 54.482_06,
    longitude: -2.900_08,
  },
  {
    remoteId: '2566',
    name: 'Little Hart Crag',
    area: 'Eastern Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Hewitt|Nuttall|Fellranger|Synge|Sim|Tump|',
    height: 637,
    notes:
      'ground 120m ENE at NY 38853 10053 and 20m NW at NY 38722 10047 is lower',
    latitude: 54.481_916,
    longitude: -2.947_169,
  },
  {
    remoteId: '2494',
    name: 'Gibson Knott',
    area: 'Central Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|Fellranger|Synge|',
    height: 420.1,
    notes:
      'Fellranger summit is the cairn 200m SE at NY 31853 09923 and is 2m higher',
    latitude: 54.481_07,
    longitude: -3.055_825,
  },
  {
    remoteId: '2456',
    name: 'Seathwaite Fell',
    area: 'Southern Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|Fellranger|Synge|',
    height: 601.1,
    notes: 'Wainwright summit cairn is 16m NW at NY 22903 10180',
    latitude: 54.480_998,
    longitude: -3.191_249,
  },
  {
    remoteId: '2564',
    name: 'Middle Dodd',
    area: 'Eastern Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|Fellranger|Synge|',
    height: 654,
    notes: 'nearby rock is higher than cairn base; ground to S is lower',
    latitude: 54.477_939,
    longitude: -2.931_566,
  },
  {
    remoteId: '2537',
    name: 'Harter Fell (Mardale)',
    area: 'Far Eastern Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Hewitt|Nuttall|HuMP|sub Marilyn|Fellranger|Synge|Sim|Tump|',
    height: 779,
    notes: 'cairn is built on largely hidden small outcrop of rock',
    latitude: 54.476_414,
    longitude: -2.835_323,
  },
  {
    remoteId: '2396',
    name: 'High Raise',
    area: 'Central Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Marilyn|Hewitt|Nuttall|HuMP|Fellranger|Synge|Sim|Tump|',
    height: 762,
    notes:
      'rock 30cm higher than flush bracket; windshelter conceal higher rock',
    latitude: 54.475_962,
    longitude: -3.111_268,
  },
  {
    remoteId: '2498',
    name: 'Helm Crag',
    area: 'Central Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|Fellranger|Synge|Tump|',
    height: 405,
    notes: '',
    latitude: 54.475_026,
    longitude: -3.040_823,
  },
  {
    remoteId: '2468',
    name: 'Tarn Crag (Easedale)',
    area: 'Central Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|Fellranger|Synge|',
    height: 549,
    notes:
      'cairn is Wainwright and Birkett; it is c 3m lower than highest point of fell 100m WNW at NY 30277 09335',
    latitude: 54.474_295,
    longitude: -3.076_006,
  },
  {
    remoteId: '2601',
    name: 'Stone Arthur',
    area: 'Eastern Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|Fellranger|Synge|',
    height: 504,
    notes: 'ground 25m N at NY 34774 09250 is at least as high',
    latitude: 54.474_276,
    longitude: -3.008_366,
  },
  {
    remoteId: '2562',
    name: 'High Pike (Scandale)',
    area: 'Eastern Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|Fellranger|Synge|',
    height: 656,
    notes:
      'Wainwright summit; highest point on E side of wall but note ground 25m to W (NY 37420 08821) on other side of wall is as high',
    latitude: 54.470_976,
    longitude: -2.966_791,
  },
  {
    remoteId: '2538',
    name: 'Red Screes',
    area: 'Eastern Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Marilyn|Hewitt|Nuttall|HuMP|Fellranger|Synge|Sim|Tump|',
    height: 776,
    notes: 'trig point is at NY 39650 08771; rock 13m NW is 5cm lower',
    latitude: 54.470_589,
    longitude: -2.932_572,
  },
  {
    remoteId: '2407',
    name: 'Sergeant Man',
    area: 'Central Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|Fellranger|Synge|deleted Nuttall|',
    height: 736,
    notes: '',
    latitude: 54.470_362,
    longitude: -3.102_552,
  },
  {
    remoteId: '2548',
    name: 'Froswick',
    area: 'Far Eastern Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Hewitt|Nuttall|Fellranger|Synge|Sim|Tump|',
    height: 720,
    notes: '',
    latitude: 54.468_949,
    longitude: -2.872_974,
  },
  {
    remoteId: '2388',
    name: 'Allen Crags',
    area: 'Southern Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Hewitt|Nuttall|Fellranger|Synge|Sim|Tump|',
    height: 785,
    notes: '',
    latitude: 54.466_367,
    longitude: -3.179_175,
  },
  {
    remoteId: '2573',
    name: 'Heron Pike (Rydal)',
    area: 'Eastern Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|Nuttall|Synge|sub Sim|',
    height: 612,
    notes: 'cairn has been destroyed',
    latitude: 54.466_072,
    longitude: -2.995_142,
  },
  {
    remoteId: '2364',
    name: 'Great End',
    area: 'Southern Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Hewitt|Nuttall|Fellranger|Synge|Sim|Tump|',
    height: 909.5,
    notes: 'cairn 160m W at NY 22532 08465 is c 1m lower',
    latitude: 54.464_94,
    longitude: -3.194_548,
  },
  {
    remoteId: '2450',
    name: 'Yewbarrow',
    area: 'Western Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Hewitt|Nuttall|HuMP|sub Marilyn|Fellranger|Synge|Sim|Tump|',
    height: 628.7,
    notes: '',
    latitude: 54.464_889,
    longitude: -3.276_86,
  },
  {
    remoteId: '2427',
    name: 'Seatallan',
    area: 'Western Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Marilyn|Hewitt|Nuttall|HuMP|Fellranger|Synge|Sim|Tump|',
    height: 692,
    notes:
      'summit is 55m NE of trig point (NY 13963 08402) and 15m SSW of small cairn (NY 14008 08455)',
    latitude: 54.464_065,
    longitude: -3.328_274,
  },
  {
    remoteId: '2559',
    name: 'Tarn Crag (Sleddale)',
    area: 'Far Eastern Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Marilyn|Hewitt|Nuttall|HuMP|Fellranger|Synge|Sim|Tump|',
    height: 664,
    notes:
      'cairn is NE of pillar (NY 48784 07802); pointed rock on grassy rise 60m WNW at NY 48786 07863 is of equal height',
    latitude: 54.463_458,
    longitude: -2.790_658,
  },
  {
    remoteId: '2382',
    name: 'Lingmell',
    area: 'Southern Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Hewitt|Nuttall|Fellranger|Synge|Sim|Tump|',
    height: 807,
    notes: 'finger of rock on N top is at least as high',
    latitude: 54.462_803,
    longitude: -3.2213,
  },
  {
    remoteId: '2546',
    name: 'Kentmere Pike',
    area: 'Far Eastern Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Hewitt|Nuttall|Fellranger|Synge|Sim|Tump|',
    height: 730.5,
    notes:
      'trig point is 3m E of wall; cairn 3m W of wall is lower; other outcrops in summit area are all lower',
    latitude: 54.462_682,
    longitude: -2.826_034,
  },
  {
    remoteId: '2413',
    name: 'Thunacar Knott',
    area: 'Central Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|Nuttall|Fellranger|Synge|sub Sim|',
    height: 723,
    notes: 'Wainwright summit is mound 50m north of tarn NY 27925 08144',
    latitude: 54.462_189,
    longitude: -3.112_653,
  },
  {
    remoteId: '2596',
    name: 'Low Pike',
    area: 'Eastern Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|Fellranger|Synge|',
    height: 508,
    notes: '',
    latitude: 54.462_069,
    longitude: -2.967_985,
  },
  {
    remoteId: '2542',
    name: 'Ill Bell',
    area: 'Far Eastern Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Hewitt|Nuttall|HuMP|Fellranger|Synge|Sim|Tump|',
    height: 757,
    notes: 'S cairn at NY 43660 07720 is c 50cm lower',
    latitude: 54.462_017,
    longitude: -2.870_837,
  },
  {
    remoteId: '2423',
    name: 'Pavey Ark',
    area: 'Central Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|Nuttall|Fellranger|Synge|',
    height: 700,
    notes: '',
    latitude: 54.461_494,
    longitude: -3.105_214,
  },
  {
    remoteId: '2470',
    name: 'Blea Rigg',
    area: 'Central Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|Fellranger|Synge|',
    height: 541,
    notes:
      'Wainwright summit; rocky knoll 80m WSW at NY 30079 07807 is c 3m higher',
    latitude: 54.461_076,
    longitude: -3.078_806,
  },
  {
    remoteId: '2437',
    name: 'Rossett Pike',
    area: 'Southern Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Hewitt|Nuttall|Fellranger|Synge|Sim|Tump|',
    height: 651,
    notes: '',
    latitude: 54.457_935,
    longitude: -3.159_804,
  },
  {
    remoteId: '2565',
    name: 'Grey Crag',
    area: 'Far Eastern Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Hewitt|Nuttall|Fellranger|Synge|Sim|Tump|',
    height: 638,
    notes:
      'outcrop is 40m N of Wainwright cairn (NY 49713 07177) and c 1.7m higher',
    latitude: 54.457_874,
    longitude: -2.777_191,
  },
  {
    remoteId: '2369',
    name: 'Esk Pike',
    area: 'Southern Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Hewitt|Nuttall|HuMP|Fellranger|Synge|Sim|Tump|',
    height: 885,
    notes:
      'rib of rock 4mNE is as high; large cairn 30m NE at NY 23671 07527 is lower',
    latitude: 54.457_172,
    longitude: -3.179_219,
  },
  {
    remoteId: '2406',
    name: 'Harrison Stickle',
    area: 'Central Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Hewitt|Nuttall|Fellranger|Synge|Sim|Tump|',
    height: 736,
    notes: '',
    latitude: 54.456_898,
    longitude: -3.109_455,
  },
  {
    remoteId: '2611',
    name: 'Nab Scar',
    area: 'Eastern Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|Fellranger|Synge|',
    height: 450,
    notes: '',
    latitude: 54.456_414,
    longitude: -2.995_849,
  },
  {
    remoteId: '2417',
    name: 'Pike of Stickle',
    area: 'Central Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Hewitt|Nuttall|Fellranger|Synge|Sim|Tump|',
    height: 708.4,
    notes: '',
    latitude: 54.456_393,
    longitude: -3.121_381,
  },
  {
    remoteId: '2430',
    name: 'Loft Crag',
    area: 'Central Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|Nuttall|Fellranger|Synge|sub Sim|',
    height: 681.7,
    notes: '',
    latitude: 54.454_429,
    longitude: -3.115_991,
  },
  {
    remoteId: '2359',
    name: 'Scafell Pike',
    area: 'Southern Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Furth|Wainwright|Birkett|Marilyn|Hewitt|Nuttall|HuMP|Fellranger|Synge|Sim|County Top - Administrative|County Top - Historic|County Top - Current County and Unitary Authority|Tump|',
    height: 978.07,
    notes: '',
    latitude: 54.454_263,
    longitude: -3.211_682,
  },
  {
    remoteId: '2459',
    name: 'Middle Fell',
    area: 'Western Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Dodd|Dewey|HuMP|Fellranger|Synge|Tump|',
    height: 582,
    notes: '',
    latitude: 54.453_249,
    longitude: -3.311_327,
  },
  {
    remoteId: '2551',
    name: 'Yoke',
    area: 'Far Eastern Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Hewitt|Nuttall|Fellranger|Synge|Sim|Tump|',
    height: 707,
    notes: '',
    latitude: 54.452_928,
    longitude: -2.868_731,
  },
  {
    remoteId: '2499',
    name: 'Silver How',
    area: 'Central Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|Fellranger|Synge|',
    height: 393.8,
    notes: 'ground 5m NW is of similar height',
    latitude: 54.450_687,
    longitude: -3.042_89,
  },
  {
    remoteId: '2626',
    name: 'Troutbeck Tongue',
    area: 'Far Eastern Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|Fellranger|Synge|Tump|',
    height: 364,
    notes:
      'knoll is 40m N of cairn (NY 42233 06386) and 2m higher; cairn is Birkett and Wainwright summit',
    latitude: 54.449_952,
    longitude: -2.892_312,
  },
  {
    remoteId: '2574',
    name: 'Shipman Knotts',
    area: 'Far Eastern Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|Fellranger|Synge|',
    height: 587,
    notes:
      'small cairn by wall 90m N at NY 47254 06306 (Birkett) is c 40cm lower; rock 3m W of wall is c 30cm lower',
    latitude: 54.448_577,
    longitude: -2.814_707,
  },
  {
    remoteId: '2365',
    name: 'Bowfell',
    area: 'Southern Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Hewitt|Nuttall|HuMP|sub Marilyn|Fellranger|Synge|Sim|Tump|',
    height: 902.9,
    notes: '',
    latitude: 54.447_816,
    longitude: -3.166_242,
  },
  {
    remoteId: '2360',
    name: 'Scafell',
    area: 'Southern Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Furth|Wainwright|Birkett|Hewitt|Nuttall|HuMP|Fellranger|Synge|Sim|Tump|',
    height: 963.9,
    notes: '',
    latitude: 54.447_498,
    longitude: -3.224_731,
  },
  {
    remoteId: '2497',
    name: 'Buckbarrow',
    area: 'Western Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|Fellranger|Synge|',
    height: 423,
    notes: '',
    latitude: 54.443_165,
    longitude: -3.334_275,
  },
  {
    remoteId: '2607',
    name: 'Baystones',
    area: 'Far Eastern Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|HuMP|sub Marilyn|Fellranger|Tump|',
    height: 486.9,
    notes:
      'mound 130m NE at NY 40355 05275 is 0.83m lower and is Hill 3838, the 487m spot height on 1:50000 map',
    latitude: 54.438_194,
    longitude: -2.921_751,
  },
  {
    remoteId: '2507',
    name: 'Loughrigg Fell',
    area: 'Central Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|Marilyn|HuMP|Fellranger|Synge|Tump|',
    height: 335,
    notes: '',
    latitude: 54.437_454,
    longitude: -3.008_355,
  },
  {
    remoteId: '2397',
    name: 'Slight Side',
    area: 'Southern Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|Fellranger|Synge|deleted Nuttall|',
    height: 762,
    notes: 'tor 40m NW at NY 20970 05030 is 30cm lower',
    latitude: 54.434_392,
    longitude: -3.219_575,
  },
  {
    remoteId: '2371',
    name: 'Crinkle Crags - Long Top',
    area: 'Southern Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Hewitt|Nuttall|HuMP|Fellranger|Synge|Sim|Tump|',
    height: 859,
    notes: 'North cairn is higher than South cairn',
    latitude: 54.433_704,
    longitude: -3.159_813,
  },
  {
    remoteId: '2454',
    name: 'Illgill Head',
    area: 'Southern Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Marilyn|Dewey|HuMP|Fellranger|Synge|Sim|Tump|',
    height: 608.8,
    notes:
      'higher by 0.5m than rock by windshelter at NY16905 05025; rock 30m SW at NY 16874 04908 is 0.04m lower',
    latitude: 54.432_93,
    longitude: -3.282_634,
  },
  {
    remoteId: '2485',
    name: 'Lingmoor Fell',
    area: 'Southern Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|Marilyn|HuMP|Fellranger|Synge|Tump|',
    height: 470,
    notes: '',
    latitude: 54.432_067,
    longitude: -3.076_41,
  },
  {
    remoteId: '2590',
    name: 'Sallows',
    area: 'Far Eastern Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|Dodd|Dewey|Fellranger|Synge|Tump|',
    height: 516,
    notes: '',
    latitude: 54.428_122,
    longitude: -2.869_995,
  },
  {
    remoteId: '2419',
    name: 'Pike of Blisco',
    area: 'Southern Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Marilyn|Hewitt|Nuttall|HuMP|Fellranger|Synge|Sim|Tump|',
    height: 705,
    notes: 'North cairn is higher than South cairn',
    latitude: 54.428_111,
    longitude: -3.124_925,
  },
  {
    remoteId: '2422',
    name: 'Cold Pike',
    area: 'Southern Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Hewitt|Nuttall|Fellranger|Synge|Sim|Tump|',
    height: 700.1,
    notes: '',
    latitude: 54.4226,
    longitude: -3.137_582,
  },
  {
    remoteId: '2609',
    name: 'Sour Howes',
    area: 'Far Eastern Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|Synge|Tump|',
    height: 483,
    notes:
      "Wainwright's summit is probably shaly ridge 60m ESE NY 42832 03198; Wainwright's sketch map may be misleading as it indicates summit is further SW where ground is obviously lower",
    latitude: 54.421_166,
    longitude: -2.883_595,
  },
  {
    remoteId: '2473',
    name: 'Whin Rigg (Wasdale)',
    area: 'Southern Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|Dodd|Dewey|Fellranger|Synge|Tump|',
    height: 537,
    notes:
      'rock 3m E of cairn is highest point of fell; cairn 100m SSE on S top at NY 15138 03442 is about 1m lower; rock 100m SSE on S top at NY 15148 03435 is about 0.7m lower',
    latitude: 54.420_162,
    longitude: -3.309_916,
  },
  {
    remoteId: '2469',
    name: 'Hard Knott',
    area: 'Southern Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Marilyn|Dodd|Dewey|HuMP|Fellranger|Synge|Tump|',
    height: 549,
    notes: 'top 200m SW is lower',
    latitude: 54.411_026,
    longitude: -3.185_029,
  },
  {
    remoteId: '2508',
    name: 'Black Fell',
    area: 'Southern Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|HuMP|Fellranger|Synge|Tump|',
    height: 323,
    notes: 'rock 55m N of trig point (NY 34041 01641) is as high',
    latitude: 54.405_503,
    longitude: -3.017_955,
  },
  {
    remoteId: '2640',
    name: 'Wetherlam',
    area: 'Southern Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Hewitt|Nuttall|HuMP|sub Marilyn|Fellranger|Synge|Sim|Tump|',
    height: 763,
    notes: '',
    latitude: 54.400_488,
    longitude: -3.097_966,
  },
  {
    remoteId: '2637',
    name: 'Great Carrs',
    area: 'Southern Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|Nuttall|Fellranger|Synge|sub Sim|',
    height: 785,
    notes: '',
    latitude: 54.398_777,
    longitude: -3.124_738,
  },
  {
    remoteId: '2673',
    name: 'Holme Fell',
    area: 'Southern Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|Marilyn|HuMP|Fellranger|Synge|Tump|',
    height: 316,
    notes:
      'cairn on large rock outcrop (Birkett) 60m NNE at NY 31531 00657 is 0.5m lower; rock outcrop 110m NNE at NY 31557 00699 is 0.3m lower',
    latitude: 54.396_301,
    longitude: -3.056_527,
  },
  {
    remoteId: '2635',
    name: 'Swirl How',
    area: 'Southern Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Hewitt|Nuttall|HuMP|Fellranger|Synge|Sim|Tump|',
    height: 802.4,
    notes: '',
    latitude: 54.395_257,
    longitude: -3.121_515,
  },
  {
    remoteId: '2639',
    name: 'Grey Friar',
    area: 'Southern Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Hewitt|Nuttall|Fellranger|Synge|Sim|Tump|',
    height: 773,
    notes: 'cairn 40m NW at NY 25989 00396 is about 50cm lower',
    latitude: 54.393_339,
    longitude: -3.141_054,
  },
  {
    remoteId: '2643',
    name: 'Harter Fell (Eskdale)',
    area: 'Southern Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Marilyn|Hewitt|Nuttall|HuMP|Fellranger|Synge|Sim|Tump|',
    height: 653.2,
    notes: 'rock tor 20m ENE is 1.6m lower',
    latitude: 54.386_916,
    longitude: -3.204_523,
  },
  {
    remoteId: '2636',
    name: 'Brim Fell',
    area: 'Southern Fells',
    county: 'Cumbria',
    country: 'England',
    classification: '|Wainwright|Birkett|Nuttall|Fellranger|Synge|',
    height: 795.9,
    notes: '',
    latitude: 54.377_283,
    longitude: -3.124_197,
  },
  {
    remoteId: '2655',
    name: 'Green Crag',
    area: 'Southern Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|HuMP|sub Marilyn|Fellranger|Synge|Tump|',
    height: 488.7,
    notes: 'rib of rock 25m NE of summit at SD 20032 98292 is 2cm lower',
    latitude: 54.373_706,
    longitude: -3.232_832,
  },
  {
    remoteId: '2634',
    name: 'The Old Man of Coniston',
    area: 'Southern Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Marilyn|Hewitt|Nuttall|HuMP|County Top - Historic|Fellranger|Synge|Sim|Tump|',
    height: 802.4,
    notes: '',
    latitude: 54.370_658,
    longitude: -3.121_445,
  },
  {
    remoteId: '2638',
    name: 'Dow Crag',
    area: 'Southern Fells',
    county: 'Cumbria',
    country: 'England',
    classification:
      '|Wainwright|Birkett|Hewitt|Nuttall|HuMP|Fellranger|Synge|Sim|Tump|',
    height: 778,
    notes: '',
    latitude: 54.3703,
    longitude: -3.136_659,
  },
]

const seedHill = async (prisma: PrismaClient) => {
  const { default: pMap } = await import('p-map')

  await pMap(
    hillList,
    (hill) => {
      return prisma.hill.upsert({
        where: {
          remoteId: hill.remoteId,
        },
        update: hill,
        create: hill,
      })
    },
    { concurrency: 1 },
  )
}

module.exports = { hillList, seedHill }
